### ISSUE TITLE
Incompatibility with 2.9.2 version of jackson

### ISSUE THREAD

**Issue by mcvsubbu** [eclipse-ee4j/jersey#3838]
Jersey seems to be incompatible with jackson-databind 2.9.2. Unfortunately we have a situation where 2.9.2 is pulled in due to other dependencies, and jersey fails with an exception like this (even before any of our methods get called back).  Would it be possible to release a newer version of jersey that does not use the deprecated method from jackson?

java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.util.BeanUtil.okNameForSetter(Lcom/fasterxml/jackson/databind/introspect/AnnotatedMethod;)Ljava/lang/String;
    at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector.findNameForDeserialization(JaxbAnnotationIntrospector.java:1008)
    at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findNameForDeserialization(AnnotationIntrospectorPair.java:749)
    at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addSetterMethod(POJOPropertiesCollector.java:620)
    at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addMethods(POJOPropertiesCollector.java:535)
    at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:309)
    at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:287)
    at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:170)
    at com.fasterxml.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:164)
    at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:239)
    at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._findCreatorsFromProperties(BasicDeserializerFactory.java:331)
    at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:315)
    at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:254)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:256)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:179)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:411)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
    at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
    at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
    at com.fasterxml.jackson.databind.ObjectReader._prefetchRootDeserializer(ObjectReader.java:1935)
    at com.fasterxml.jackson.databind.ObjectReader.forType(ObjectReader.java:677)
    at com.fasterxml.jackson.databind.ObjectReader.withType(ObjectReader.java:718)
    at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:804)
    at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256)
    at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235)
    at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155)
    at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:74)
    at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155)
    at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
    at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
    at org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:271)
    at org.glassfish.jersey.server.internal.inject.EntityParamValueFactoryProvider$EntityValueFactory.provide(EntityParamValueFactoryProvider.java:96)
    at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.provide(ParamValueFactoryWithSource.java:71)
    at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:94)
    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:127)
    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
    at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
    at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
    at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
    at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384)
    at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
    at java.lang.Thread.run(Thread.java:745)

**Comment by chkal** [comment]
As a workaround, you could use a dependencyManagment element in your pom to get a different version of Jackson.

**Comment by mcvsubbu** [comment]
@chkal like I mentioned, the newer version of jackson bind is pulled in due to another dependency, and we are not able to avoid that. Would it be possible to get a jersey build with the newer version of jackson?

**Comment by jansupol** [comment]
Unfortunately, this can take some time. The Jakarta EE plans are as follows:
1.   Get every remaining Java EE project to be contributed (such as Glassfish) into Jakarta EE
2.   Approve the dependencies (CQs) - For Jersey, this is an ongoing process currently.
3.   Release the initial version. Every project has EE4J_8 branch in its repo. This release would be nearly identical to Java EE 8 release.
4.   Approve new dependencies (CQs) for new release (new Jackson). This step can be done in parallel with step 3.
5.   Release new version. This release can contain new version of Jackson.

**Comment by jansupol** [comment]
On the second thought, version 2.8.10 was chosen to be in sync with glassfish...

**Comment by mcvsubbu** [comment]
Thanks, @jansupol . I am not sure i understand what this means for upgrading to newer version of jackson. Can we still expect the steps you had outlined before to move forward? If so, what may be the timeframe we can get a newer version? thanks again.

**Comment by chkal** [comment]
> @chkal like I mentioned, the newer version of jackson bind is pulled in due to another dependency, and we are not able to avoid that. Would it be possible to get a jersey build with the newer version of jackson?

Sure, but even if this new Jackson version is pulled in by another dependency, you can change the version pulled in using `<dependencyManagement>` in your local pom. But of cause only if the component depending on the new Jackson version works with older ones.

**Comment by jansupol** [comment]
Glassfish upgraded to 2.9.4 last week so I assume we are free to go with Step 4.

**Comment by jansupol** [comment]
For the time frame, see Jakarta EE initial release timeframe; I assume we can upgrade in the initial release (EE4_J branch)

**Comment by mcvsubbu** [comment]
@chkal for now I have done something similar. It is only a question of time when the other component starts to use some new features and hits the same problem with the old version that jersey is hitting with the new version.

Since some APIs have been removed in the new version, I see no way out unless we can have jersey move forward with newer versions and stop using the deprecated APIs.

**Comment by mcvsubbu** [comment]
@jansupol thanks much for moving forward. Will look forward to 2.29.

**Comment by jansupol** [comment]
You know what? I labeled that wrong, it should be 2.28 :)

**Comment by mcvsubbu** [comment]
@jansupol do we have an ETA  date for 2.28?

**Comment by jansupol** [comment]
@mcvsubbu 2.28 is the initial release. As soon as all the projects are contributed to the Eclipse Foundation, the initial release of whole Jakarta EE and all projects in the umbrella (and Jersey 2.28) should take place. I know it should happen rather soon, but the exact date should be communicated either by the foundation or by PMC.

**Comment by mcvsubbu** [comment]
@jansupol do we have a date for 2.28 yet? thanks.

**Comment by jansupol** [comment]
There is no official release date, yet. I assume it will be announced on [EclipseCon](https://www.eclipsecon.org/europe2018/news/welcome-eclipsecon-europe-2018) / [Code One](https://www.oracle.com/code-one/index.html).

**Comment by mcvsubbu** [comment]
@jansupol  do we have a date for a release with the new json package?

**Comment by jansupol** [comment]
Jersey 2.28 contains Jackson 2.9.6 dependency
CQ 17606,17607,17608,17609,17610
