### ISSUE TITLE
 java.lang.InternalError: Unexpected CryptoAPI failure generating seed in create()

### ISSUE THREAD

**Issue by camilla11** [eclipse-ee4j/jersey#3880]
```
38513 | 09:03.4 | Logging in... Jun 22, 2018 1:09:02 PM   com.sun.jersey.core.spi.component.ProviderFactory __getComponentProvider
-- | -- | --
38514 | 09:03.4 | SEVERE: The provider class, class   com.sun.jersey.multipart.impl.MultiPartReaderClientSide, could not be   instantiated. Processing will continue but the class will not be utilized
38515 | 09:03.4 | java.lang.InternalError: Unexpected CryptoAPI failure generating seed
38516 | 09:03.4 | at sun.security.provider.NativeSeedGenerator.getSeedBytes(Unknown   Source)
38517 | 09:03.4 | at sun.security.provider.SeedGenerator.generateSeed(Unknown Source)
38518 | 09:03.4 | at   sun.security.provider.SecureRandom$SeederHolder.<clinit>(Unknown   Source)
38519 | 09:03.4 | at sun.security.provider.SecureRandom.engineNextBytes(Unknown Source)
38520 | 09:03.4 | at java.security.SecureRandom.nextBytes(Unknown Source)
38521 | 09:03.4 | at java.security.SecureRandom.next(Unknown Source)
38522 | 09:03.4 | at java.util.Random.nextLong(Unknown Source)
38523 | 09:03.4 | at java.io.File$TempDirectory.generateFile(Unknown Source)
38524 | 09:03.4 | at java.io.File.createTempFile(Unknown Source)
38525 | 09:03.4 | at java.io.File.createTempFile(Unknown Source)
38526 | 09:03.4 | at   com.sun.jersey.multipart.impl.MultiPartReaderClientSide.createMimeConfig(MultiPartReaderClientSide.java:121)
38527 | 09:03.4 | at   com.sun.jersey.multipart.impl.MultiPartReaderClientSide.<init>(MultiPartReaderClientSide.java:109)
38528 | 09:03.4 | at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
38529 | 09:03.4 | at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
38530 | 09:03.4 | at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown   Source)
38531 | 09:03.4 | at java.lang.reflect.Constructor.newInstance(Unknown Source)
38532 | 09:03.4 | at   com.sun.jersey.core.spi.component.ComponentConstructor._getInstance(ComponentConstructor.java:210)
38533 | 09:03.4 | at   com.sun.jersey.core.spi.component.ComponentConstructor.getInstance(ComponentConstructor.java:180)
38534 | 09:03.4 | at   com.sun.jersey.core.spi.component.ProviderFactory.__getComponentProvider(ProviderFactory.java:166)
38535 | 09:03.4 | at   com.sun.jersey.core.spi.component.ProviderFactory.getComponentProvider(ProviderFactory.java:137)
38536 | 09:03.4 | at   com.sun.jersey.core.spi.component.ProviderServices.getComponent(ProviderServices.java:283)
38537 | 09:03.4 | at   com.sun.jersey.core.spi.component.ProviderServices.getServices(ProviderServices.java:163)
38538 | 09:03.4 | at   com.sun.jersey.core.spi.factory.MessageBodyFactory.initReaders(MessageBodyFactory.java:176)
38539 | 09:03.4 | at   com.sun.jersey.core.spi.factory.MessageBodyFactory.init(MessageBodyFactory.java:162)
38540 | 09:03.4 | at com.sun.jersey.api.client.Client.init(Client.java:343)
38541 | 09:03.4 | at com.sun.jersey.api.client.Client.access$000(Client.java:119)
38542 | 09:03.4 | at com.sun.jersey.api.client.Client$1.f(Client.java:192)
38543 | 09:03.4 | at com.sun.jersey.api.client.Client$1.f(Client.java:188)
38544 | 09:03.4 | at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
38545 | 09:03.4 | at com.sun.jersey.api.client.Client.<init>(Client.java:188)
38546 | 09:03.4 | at com.sun.jersey.api.client.Client.<init>(Client.java:160)
38547 | 09:03.4 | at com.sun.jersey.api.client.Client.create(Client.java:673)
38548 | 09:03.4 | at   org.vena.etltool.JerseyClientFactory.create(JerseyClientFactory.java:9)


```

**Comment by jansupol** [comment]
There is a [nice article on StackOverflow](https://stackoverflow.com/help/how-to-ask) that can help with filing a bug next time. Without a reproducer or more information, it really is impossible to answer. 
Also, the stacktrace suggest you still use Jersey 1.x. I am closing the issue.
