### ISSUE TITLE
Geeting errors on Jersey JARs while creating a RESTful API in tomcat8, eclipse

### ISSUE THREAD

**Issue by AritraDB** [eclipse-ee4j/jersey#4106]
Geeting errors on Jersey JARs while creating a RESTful API in tomcat8, eclipse. I'm using jdk1.8.0_171 and Apache-Tomcat-8.0.24.

   1. I have created a Dynamic Web Project in Eclipse.
   2. Put all the JARs into MyProject->WebContent->WEB-INF->lib, which has been downloaded from https://jersey.github.io/download.html.
   3. Define the servlet-name,servlet-class,init-param,servlet-mapping etc in web.xml file.
   4. Create a package (wsdemo2) under the src folder and create a java class (wsdemo2.java) also which contains a public class and a public method.
   5. I have used annotations like @Path("/name"),@GET,@Produces(MediaType.TEXT_HTML),@Path("{name}")
  6.  Compiled successfully but whenever I'm trying to start the server, it occurs few ClassFormatException on few Jersey JARs like- jakarta.json-api-1.1.5.jar, yasson-1.0.3.jar, jakarta.ws.rs-api-2.1.5.jar, jakarta.json.bind-api-1.0.1.jar, jakarta.xml.bind-api-2.3.2.jar.

error:
2019 12:33:21 PM org.apache.catalina.startup.ContextConfig processAnnotationsJar
SEVERE: Unable to process Jar entry [module-info.class] from Jar [jar:file:/E:/DemoUser/Demo%20Tomcat%20Workspace/apache-tomcat-8.0.24/webapps/MyProject/WEB-INF/lib/jakarta.json-api-1.1.5.jar!/] for annotations
org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
    at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:97)
    at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPool.java:55)
    at org.apache.tomcat.util.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:176)
    at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:85)
    at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2011)
    at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:1961)
    at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1936)
    at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1897)
    at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1149)
    at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:771)
    at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:305)
    at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5066)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

web.xml
```
<servlet>
      <servlet-name>JAVA WS</servlet-name>
      <servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>
  <init-param>
      <param-name>jersey.config.server.provider.packages</param-name>
      <param-value>wsdemo2</param-value>
  </init-param>
  <load-on-startup>1</load-on-startup>
  </servlet>
  <servlet-mapping>
  <servlet-name>JAVA WS</servlet-name>
  <url-pattern>/*</url-pattern>
  </servlet-mapping>
```

wsdemo2;
```
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
@Path("/wsdemo2")
public class wsdemo2 {
    @GET
    @Produces(MediaType.TEXT_HTML)
    @Path("{name}")
    public String sayhello2(@PathParam("name") String name) {
        String response = "<h1>Your name is > "+name+"</h1>";
        return response;
    }
}
```

**Comment by AritraDB** [comment]
Solved.
I used Jersey version - jaxrs-ri-2.28. 
But whenever I downgrade the JAR's version (I used Jersey 2.0) it works for me. I don't know, but looks like there are some issues in 2.28 version's JARs.

**Comment by chkal** [comment]
The problem is that Jersey 2.28 depends on API JARs which contain the JDK9 module descriptor (the file `module-info.class`). But you are using Apache Tomcat 8.0.24 which is known to fail in the annotation scanning phase if it tries to analyze the module descriptor. Updating your Apache Tomcat to a newer version should actually fix the problem. IIRC versions newer than ~8.0.40 should work.

**Comment by AritraDB** [comment]
> 
> 
> The problem is that Jersey 2.28 depends on API JARs which contain the JDK9 module descriptor (the file `module-info.class`). But you are using Apache Tomcat 8.0.24 which is known to fail in the annotation scanning phase if it tries to analyze the module descriptor. Updating your Apache Tomcat to a newer version should actually fix the problem. IIRC versions newer than ~8.0.40 should work.

Oh I see. Thanks for the information @chkal
