### ISSUE TITLE
Jetty, Weld and Jersey

### ISSUE THREAD

**Issue by PavelKastornyy** [eclipse-ee4j/jersey#4121]
I am using Jetty 9.4.14, Jersey 2.28 and Weld (servlet-shaded) 3.1.0. In order to link Jetty and Weld I add to the web.xml of a web application this code:

```
<listener>
    <listener-class>org.jboss.weld.environment.servlet.Listener</listener-class>
</listener>
<resource-env-ref>
    <description>Object factory for the CDI Bean Manager</description>
    <resource-env-ref-name>BeanManager</resource-env-ref-name>
    <resource-env-ref-type>javax.enterprise.inject.spi.BeanManager</resource-env-ref-type>
</resource-env-ref>
```
So Jetty + Weld works fine. Now I want to use Weld as DI container for Jersey. To get it I added the following dependencies:

	//Jersey:
	jaxb-api-2.3.0.jar
	jaxb-core-2.3.0.1.jar
	jaxb-impl-2.3.0.1.jar
	javax.ws.rs-api-2.1.1.jar
	javax.activation-1.2.0.jar
	jersey-container-jetty-http-2.28.jar
	jersey-container-servlet-core-2.28.jar
	jersey-server-2.28.jar
	jersey-common-2.28.jar
	jersey-client-2.28.jar
	//Jersey + CDI:
	bean-validator-2.5.0-b06.jar
	jersey-cdi1x-2.28.jar
	jersey-cdi1x-servlet-2.28.jar
	jersey-weld2-se-2.28.jar
	hk2-api-2.5.0.jar

And this is what I get:
```
Caused by: java.lang.IllegalStateException: InjectionManagerFactory not found.
at org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:74) ~[jersey-common-2.28.jar:?]
at java.util.Optional.orElseThrow(Optional.java:408) ~[?:?]
at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:74) ~[jersey-common-2.28.jar:?]
at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:69) ~[jersey-common-2.28.jar:?]
at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:258) ~[jersey-server-2.28.jar:?]
at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311) ~[jersey-container-servlet-core-2.28.jar:?]
at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154) ~[jersey-container-servlet-core-2.28.jar:?]
at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:346) ~[jersey-container-servlet-core-2.28.jar:?]
at javax.servlet.GenericServlet.init(GenericServlet.java:244) ~[javax.servlet-api-and-schemas-3.1.0.jar:?]
at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:672) ~[jetty-servlet-9.4.14.v20181114.jar:?]
```
If I add
```
jersey-hk2-2.28.jar
hk2-utils-2.5.0.jar
```

I get

```
Caused by: java.lang.IllegalStateException: No generator was provided and there is no default generator registered
at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.internalCreate(ServiceLocatorFactoryImpl.java:285) ~[hk2-api-2.5.0.jar:?]
at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.create(ServiceLocatorFactoryImpl.java:245) ~[hk2-api-2.5.0.jar:?]
at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.createLocator(AbstractHk2InjectionManager.java:90) ~[jersey-hk2-2.28.jar:?]
at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.<init>(AbstractHk2InjectionManager.java:62) ~[jersey-hk2-2.28.jar:?]
at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.<init>(ImmediateHk2InjectionManager.java:38) ~[jersey-hk2-2.28.jar:?]
at org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory$Hk2InjectionManagerStrategy$1.createInjectionManager(Hk2InjectionManagerFactory.java:55) ~[jersey-hk2-2.28.jar:?]
at org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory.create(Hk2InjectionManagerFactory.java:73) ~[jersey-hk2-2.28.jar:?]
at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:69) ~[jersey-common-2.28.jar:?]
at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:258) ~[jersey-server-2.28.jar:?]
at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311) ~[jersey-container-servlet-core-2.28.jar:?]
at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154) ~[jersey-container-servlet-core-2.28.jar:?]
at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:346) ~[jersey-container-servlet-core-2.28.jar:?]
at javax.servlet.GenericServlet.init(GenericServlet.java:244) ~[javax.servlet-api-and-schemas-3.1.0.jar:?]
at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:672) ~[jetty-servlet-9.4.14.v20181114.jar:?]
```
The only information how to work in such configuration I found [here](https://blogs.oracle.com/japod/container-agnostic-cdi-support-in-jersey):

> Another Servlet container that is supported by Weld is Jetty. Jersey CDI integration module should work there as well, but things have not been tested by Jersey team.

Could anyone say how to make this configuration work?

**Comment by jansupol** [comment]
Have you tried to add hk2-locator.jar?

**Comment by PavelKastornyy** [comment]
@jansupol I added `hk2-locator-2.5.0.jar` and this is the result:

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
at org.glassfish.jersey.server.ExternalRequestScopeConfigurator.init(ExternalRequestScopeConfigurator.java:60) ~[jersey-server-2.28.jar:?]
at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:335) ~[jersey-server-2.28.jar:?]
at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:292) ~[jersey-server-2.28.jar:?]
at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.28.jar:?]
at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.28.jar:?]
at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232) ~[jersey-common-2.28.jar:?]
at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:291) ~[jersey-server-2.28.jar:?]
at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:258) ~[jersey-server-2.28.jar:?]
at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311) ~[jersey-container-servlet-core-2.28.jar:?]
at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154) ~[jersey-container-servlet-core-2.28.jar:?]
at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:346) ~[jersey-container-servlet-core-2.28.jar:?]
at javax.servlet.GenericServlet.init(GenericServlet.java:244) ~[javax.servlet-api-and-schemas-3.1.0.jar:?]
at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:672) ~[jetty-servlet-9.4.14.v20181114.jar:?]
... 40 more
```

**Comment by jansupol** [comment]
I believe the issue is due to the useage of jersey-weld2-se-2.28.jar. As the "se" name suggests, this is to be used with Java SE environment, where there is no weld provided, unlike in your case, where you have Weld running in Jetty already.

**Comment by PavelKastornyy** [comment]
@jansupol Thank you very much for your help! I removed jersey-weld2-se-2.28.jar and everything seems to work. I used `jersey-weld2-se` because I saw it in [cdi-webapp pom](https://github.com/eclipse-ee4j/jersey/blob/master/examples/cdi-webapp/pom.xml). I got surprised but thought they know the topic better. 

What really confused me is the necessity of `hk2-*` and `jersey-hk2` dependencies. I still don't understand why we use them if we use Weld. Could you explain? 

And could you say - if it is safe to use this configuration when we have multiple web applications deployed in Jetty and every application uses CDI?

**Comment by jansupol** [comment]
CDI WebApp starts Weld on its own, so it uses the `jersey-weld2-se.jar`. This is not your case.

Jersey uses HK2 for the JAX-RS injections, like `@Context`, so it needs the HK2 dependencies. Only CDI specific injections are passed to CDI.

Yes, Jersey is production ready JAX-RS implementation that is safe to use in an environment with multiple applications using CDI.

**Comment by PavelKastornyy** [comment]
@jansupol Thank you for detailed answer. And the last question. This is my resource

```
@Path("myresource")
public class MyResource {
    
    @Inject
    private MyBean bean;
 
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String getIt() {
        return bean.getTest();
    }
}
```
and this is my bean:
```
@ApplicationScoped
public class MyBean {
    
    public String getTest() {
        return "This is a string from MyBean";
    }
}
```
When in `beans.xml` `bean-discovery-mode="all"` everything works - bean is injected in resource. However, when I set `bean-discovery-mode="annotated"` I get 

```
org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available for injection at SystemInjecteeImpl(requiredType=MyBean,parent=MyResource,qualifiers={},position=-1,optional=false,self=false,unqualified=null,1883164128)
at hk2.locator@2.5.0/org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:51)
```
Must I register by beans via code or there is a problem in my configuration?

**Comment by jansupol** [comment]
Possibly, you would need to annotate the Resource class with CDI Scope annotation as well.

**Comment by PavelKastornyy** [comment]
@jansupol Yes, it fixed the problem. Thank you for your help!

**Comment by luxurystorecc1** [comment]
Mastering the Modern Wardrobe: The Synthesis of Sport, Style, and Status
Introduction: The Evolution of Global Apparel
The modern wardrobe is no longer a collection of separate categories; it is a synthesis of different influences that reflect a highly mobile and active global lifestyle. Today, the technology used in a [Spain national team jersey](https://www.soccerjerseysstore.com/collections/national-teams-europe-spain) is just as refined as the craftsmanship found in a luxury evening gown. This article examines how to master this synthesis by choosing the right pieces from authoritative sources.

Footwear: The Intersection of History and Innovation
In any modern rotation, footwear serves as the anchor. The [Air Jordan 1 basketball shoes](https://www.airjordan-1.com/) remain an evergreen symbol of athletic prowess and cultural relevance. As the market for high-end sneakers expands, the [Jordan 1s high-performance silhouettes](https://www.jordan1s.com/) continue to be a top choice for those who value the heritage of the "Jumpman" legacy.

Contrasting this heritage is the futuristic approach of the [Yeezy 350 boost performance series](https://www.yeezyboost-350.com/collections/adidas-yeezy). These designs utilize cutting-edge materials to provide a fit that is both supportive and incredibly lightweight. For the ultimate in casual luxury, [comfortable Yeezy slides and foam runners](https://www.yeezyboost-350.com/) have become the definitive choice for those who want a minimalist aesthetic for their leisure time.

Authenticity in Professional Sports Merchandise
For fans of professional leagues, the jersey is a badge of honor. Finding [cheap NFL jerseys with high-quality embroidery](https://www.nflshopofficialonline-store.com/) is a priority for supporters who want to look the part during the long season. Sourcing these items from an [official NFL shop online](https://www.nflshopofficialonline-store.com/) ensures that the gear is authentic and meets the standards of the league.

This commitment to authenticity is shared across all sports. Fans of the NHL often look for gear on the [NHL official site online](https://www.custombaseball-jerseys.com/) to ensure their jerseys are game-ready. Furthermore, the accessory market has seen a surge in popularity, with [NFL headwear and team caps](https://www.cheapnfl-jerseys.com/collections/headwear-nfl-headwear) becoming essential for completing a street-ready, athletic-inspired look.

Performance Meets Luxury: The Peter Millar Aesthetic
For the modern woman who demands both fashion and functionality, [Peter Millar women's golf outerwear](https://www.peter-milla.com/collections/golf-women-s-golf-outerwear) offers a sophisticated solution for days spent on the course. These garments are designed to provide technical protection while maintaining the elegant, tailored look that the [Peter Millar apparel collection](https://www.peter-milla.com/) is known for globally. It is the perfect attire for the individual who moves seamlessly from the fairways to a refined dinner at the club.

Celebrating Occasions with Elegance and Ease
Life's most important social milestones require clothing that rises to the gravity of the occasion. For wedding guests attending ceremonies during the autumn months, selecting from a range of [fall wedding guest dresses](https://www.swim-outlet.com/collections/wedding-fall-wedding-guest) allows for a stylish celebration that respects the seasonal themes. For a truly striking and classic look, [elegant red evening dresses](https://www.swim-outlet.com/collections/dresses-red) remain a powerful choice for making a grand entrance.

The move toward inclusivity in fashion has ensured that [plus size formal dresses](https://www.cheapdressesformal.com/) are now designed with the same high-fashion aesthetics as any other line. This ensures that every individual can find a look that makes them feel confident, whether it is a [white formal gown](https://www.cheapdressesformal.com/collections/dresses-white) for a gala or a designer dress for a high school prom.

Conclusion: Quality as the Universal Language
Whether you are training with professional gear from a [high-performance swim outlet](https://www.swim-outlet.com/) or dressing for a black-tie event, the key to a successful wardrobe is quality. By choosing authoritative products that offer genuine heritage and advanced technology, you ensure that your style is prepared for any environment—from the roaring crowds of the stadium to the elegant silence of the ballroom.
