### ISSUE TITLE
Issue when invoking Google Geocode API from inside a Jersey REST service

### ISSUE THREAD

**Issue by ace-zhang18** [eclipse-ee4j/jersey#4185]
I got an issue with trying to access Google Geocode API inside a jersey REST service invocation in my backend.
When I do that, it causes an internal HTTP 400 error on the server
However, invoking the Geocode API either directly through the browser or a client call works
In addition, calling a jersey REST service which calls another jersey Rest service also works
A direct call to anything works. Nesting a jersey service inside another jersey service works. But Nesting a Google API invocation inside a jersey service fails.

Call to location service ("A")

	JerseyClient client = JerseyClientBuilder.newClient();
			
	JerseyWebTarget webTarget = client.target("http://localhost:8080/arenamaster-backend/api").path("tournaments").path("location");
			
	JerseyInvocation.Builder invocationBuilder = webTarget.request(MediaType.APPLICATION_JSON);

	String input = "10621 Braddock Road – Ste B, Fairfax, VA 22032";

	Response response = invocationBuilder
					.post(Entity.entity(input, MediaType.TEXT_PLAIN));
Location Service: ("B")

	@POST
	@Path("/location")
	@Consumes(MediaType.TEXT_PLAIN)
	@Produces(MediaType.APPLICATION_JSON)
	@CrossOrigin
	public Response getLatLngFromAddress(String address) {
		LatLng latlng = LocationUtility.geocode(address);

		return Response.status(200).entity(latlng).build();		
	}
Direct Invocation of Location Service ("C")

	String address = "10621 Braddock Road – Ste B, Fairfax, VA 22032";
			
	LatLng latlng= LocationUtility.geocode(address); 
			
	System.out.println(latlng);
Geocoding function that invokes Google Geocode API ("D")

	public static LatLng geocode(String address) {
		String address_key = address.replace(' ', '+');					
		String API_key = "***hidden***";			

		String request = "https://maps.googleapis.com/maps/api/geocode/json?address=" + address_key + "&key=" + API_key;
		JerseyClient client = JerseyClientBuilder.newClient();
		
		JerseyWebTarget webTarget = client.target(request);
		
		JerseyInvocation.Builder invocationBuilder = webTarget.request(MediaType.APPLICATION_JSON);

		Response response = invocationBuilder
				.get(Response.class);

		if (response.getStatus()/100 != 2) {
			throw new RuntimeException("Failed : HTTP error code : "
					+ response.getStatus());
		}

		String output = response.readEntity(String.class);

		LatLng latlng = null;
		
		try {
			JSONObject geocode = new JSONObject(output);
			JSONArray results = geocode.getJSONArray("results");
			JSONObject address_components = (JSONObject) results.get(0);
			JSONObject geometry = (JSONObject) address_components.get("geometry");
			JSONObject location = (JSONObject) geometry.get("location");
			latlng = new LatLng(location.getDouble("lat"), location.getDouble("lng"));
		}catch(Exception e) {
			e.printStackTrace();
		}
	
		return latlng;
	}
Call within a call sample test ("E")

	//call within a call sample test
	JerseyClient client = JerseyClientBuilder.newClient();
			
	JerseyWebTarget webTarget = client.target("http://localhost:8080/arenamaster-backend/api").path("test").path("func1");
			
	JerseyInvocation.Builder invocationBuilder = webTarget.request(MediaType.TEXT_PLAIN);

	Response response = invocationBuilder
		.get(Response.class);

	if (response.getStatus()/100 != 2) {
		throw new RuntimeException("Failed : HTTP error code : "
			+ response.getStatus());
	}

	System.out.println("Output from Server .... \n");
	String output = response.readEntity(String.class);
	System.out.println(output);

Call within a call two test service endpoints ("F")

	@GET
	@Path("/func1")
	@Produces(MediaType.TEXT_PLAIN)
	@CrossOrigin
	public Response testFunc1() {
		System.out.println("1st service invoked");
		String response = "";
		
		response = TestDAO.callSecondService();
		
		return Response.status(200).entity(response).build();
	}
	
	@GET
	@Path("/func2")
	@Produces(MediaType.TEXT_PLAIN)
	@CrossOrigin
	public Response testFunc2() {
		System.out.println("2nd service invoked");
		String response = "";
		
		response = TestDAO.getMessage();
		
		return Response.status(200).entity(response).build();
	}
Call within a call test functions: ("G")

	public static String callSecondService() {
		
		JerseyClient client = JerseyClientBuilder.newClient();
		
		JerseyWebTarget webTarget = client.target("http://localhost:8080/arenamaster-backend/api").path("test").path("func3");
		
		JerseyInvocation.Builder invocationBuilder = webTarget.request();

		Response response = invocationBuilder
				.get(Response.class);

		if (response.getStatus()/100 != 2) {
			throw new RuntimeException("Failed : HTTP error code : "
					+ response.getStatus());
		}

		System.out.println("Output from Server .... \n");
		String output = response.readEntity(String.class);
		System.out.println(output);
		
		return output;
	}
	
	public static String getMessage() {
		return "Success!"; 
	}

C-D succeeds
E-F-G succeeds
A-B-D fails and prints the stacktrace below on the server console

        java.lang.RuntimeException: Failed : HTTP error code : 400
	at utilities.LocationUtility.geocode(LocationUtility.java:38)
	at services.TournamentAlphaService.getLatLngFromAddress(TournamentAlphaService.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

Update:

Call within call test (E-F-G) works properly when the following line

` WebTarget webTarget = client.target("http://localhost:8080/arenamaster-backend/api").path("test").path("func3");`
Is replaced by this:
`WebTarget webTarget = client.target("https://en.wikipedia.org/wiki/List_of_HTTP_status_codes");`

**Comment by ace-zhang18** [comment]
Update:

Call within call test works properly when the following line

`WebTarget webTarget = client.target("http://localhost:8080/arenamaster-backend/api").path("test").path("func3");`

Is replaced by this:

`WebTarget webTarget = client.target("https://en.wikipedia.org/wiki/List_of_HTTP_status_codes");`

**Comment by ace-zhang18** [comment]
I fixed the issue by encoding the input address as thus:

`String request = "https://maps.googleapis.com/maps/api/geocode/json?address=" + new URLEncoder().encode(address_key, Charset.availableCharsets().get("UTF-8")) + "&key=" + API_key;
`		

Turns out Strings that come out of a Jersey REST endpoint are non-UTF-8. If this is an issue or not I'm not sure.

**Comment by jansupol** [comment]
What OS are you on? The default Charset is defined by OS. On Windows, the default is CP1250, Unix & MAC should have UTF-8.
