### ISSUE TITLE
Race condition in EntityFiltering

### ISSUE THREAD

**Issue by jansupol** [eclipse-ee4j/jersey#4187]
The symptom is that when an entity filtering is used, only some fields are returned, not all selected.

The log can contain an exception:
> Caused by:
        |java.util.ConcurrentModificationException
        |       at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
        |       at java.util.HashMap$EntryIterator.next(HashMap.java:1471)
        |       at java.util.HashMap$EntryIterator.next(HashMap.java:1469)
        |       at org.glassfish.jersey.internal.guava.AbstractMapBasedMultimap$AsMap$AsMapIterator.next(AbstractMapBasedMultimap.java:1348)
        |       at org.glassfish.jersey.internal.guava.AbstractMapBasedMultimap$AsMap$AsMapIterator.next(AbstractMapBasedMultimap.java:1336)
        |       at org.glassfish.jersey.internal.guava.TransformedIterator.next(TransformedIterator.java:45)
        |       at org.glassfish.jersey.internal.guava.AbstractMultimap.containsValue(AbstractMultimap.java:41)
        |       at org.glassfish.jersey.internal.guava.HashMultimap.containsValue(HashMultimap.java:44)
        |       at org.glassfish.jersey.message.filtering.EntityGraphImpl.presentInScopes(EntityGraphImpl.java:205)
        |       at org.glassfish.jersey.message.filtering.DefaultEntityProcessor.process(DefaultEntityProcessor.java:95)
        |       at org.glassfish.jersey.message.filtering.DefaultEntityProcessor.process(DefaultEntityProcessor.java:79)
        |       at org.glassfish.jersey.message.filtering.EntityInspectorImpl.inspectEntityProperties(EntityInspectorImpl.java:173)
        |       at org.glassfish.jersey.message.filtering.EntityInspectorImpl.inspect(EntityInspectorImpl.java:104)
        |       at org.glassfish.jersey.message.filtering.spi.AbstractObjectProvider.getFilteringObject (AbstractObjectProvider.java:90)

**Comment by jansupol** [comment]
When `EntityInspectorImpl.inspect` is called, two threads can start to populate the EntityGraph leading to the exception.

Also, if a first thread is still populating the EntityGraph, another thread can invoke the method, 
`graphProvider.containsEntityGraph` will return `true`, the thread can create an `ObjectGraph` from the not fully populated `EntityGraph` in `AbstractObjectProvider#getFilteringObject`.
