### ISSUE TITLE
Jetty 9.4.22 QueuedThreadPool compatibility

### ISSUE THREAD

**Issue by josephlbarnett** [eclipse-ee4j/jersey#4302]
Per, https://github.com/eclipse/jetty.project/issues/4121 QueuedThreadPool implements ThreadFactory, which makes the newThread method public instead of protected.  The JettyConnectorThreadPool class in JettyHttpContainerFactory has the newThread method marked as protected, and causes an IllegalAccessError when used at runtime (it also fails to compile if compiled against jetty 9.4.22):
```
java.lang.IllegalAccessError: 'java.lang.Thread org.glassfish.jersey.jetty.JettyHttpContainerFactory$JettyConnectorThreadPool.newThread(java.lang.Runnable)'
	at org.eclipse.jetty.util.thread.QueuedThreadPool.startThread(QueuedThreadPool.java:655)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.ensureThreads(QueuedThreadPool.java:642)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.doStart(QueuedThreadPool.java:182)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:407)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
	at org.eclipse.jetty.server.Server.doStart(Server.java:371)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.glassfish.jersey.jetty.servlet.JettyWebContainerFactory.create(JettyWebContainerFactory.java:257)
	at org.glassfish.jersey.jetty.servlet.JettyWebContainerFactory.create(JettyWebContainerFactory.java:282)
```

**Comment by joakime** [comment]
You don't need to customize the QueuedThreadPool any more.
Use the `java.util.concurrent.ThreadFactory` itself, and pass it into the `QueuedThreadPool` constructor.

See: https://www.eclipse.org/jetty/javadoc/current/org/eclipse/jetty/util/thread/QueuedThreadPool.html#%3Cinit%3E(int,int,int,int,java.util.concurrent.BlockingQueue,java.lang.ThreadGroup,java.util.concurrent.ThreadFactory)

**Comment by jansupol** [comment]
I agree with making the method public. We probably should not rely on the new `QueuedThreadPool` constructor which is available in the latest Jetty only, yet, so that people can switch back to a previous version of Jetty, should they need it.

We may change it later.

**Comment by NielsDoucet** [comment]
@jansupol This incompatibility causes a bug for anyone using the spring-boot-dependencies bom as a baseline for version management (see https://github.com/spring-projects/spring-boot/issues/19769).
In spring boot they are unable to change the minor version of both jetty and jersey due to various reasons (see linked ticket for details).

I asked about options on the jetty project (see https://github.com/eclipse/jetty.project/issues/4121), but in parallel I'd like to ask whether there is a possibility of a special 2.29.x release compatible with the new jetty API.
