### ISSUE TITLE
ClientResponse.readEntity fails if the server returns a blank Content-Type

### ISSUE THREAD

**Issue by ewanmellor** [eclipse-ee4j/jersey#4410]
o.g.jersey.client.ClientResponse.readEntity throws an exception if the server has responded with a Content-Type header with an empty string.  The exception is 'o.g.jersey.message.internal.HeaderValueException: Unable to parse "Content-Type" header value: ""' (full exception below).

There is code in InboundMessageContext.readEntity that is trying to handle an invalid mediaType by defaulting it to application/octet-stream.  (This would be the correct behavior in my opinion.)  However, that code does not work because:

1. InboundMessageContext.getMediaType is documented as returning a value or null.
2. InboundMessageContext.singleHeader is documented as returning a value, null, or throwing ProcessingException.
3. getMediaType calls singleHeader but doesn't catch exceptions.
4. readEntity doesn't catch exceptions from getMediaType either, so the fallback to application/octet-stream is not reached.  The exception bubbles up.

In my opinion, readEntity is violating its contract by throwing exceptions when they're not documented, so the fix belongs there.  However, this is a public method so that might have consequences that I'm not aware of.

```
org.glassfish.jersey.message.internal.HeaderValueException: Unable to parse "Content-Type" header value: ""
	at org.glassfish.jersey.message.internal.InboundMessageContext.exception(InboundMessageContext.java:341)
	at org.glassfish.jersey.message.internal.InboundMessageContext.singleHeader(InboundMessageContext.java:336)
	at org.glassfish.jersey.message.internal.InboundMessageContext.getMediaType(InboundMessageContext.java:449)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:872)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:811)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:298)
	at org.glassfish.jersey.client.InboundJaxrsResponse$1.call(InboundJaxrsResponse.java:91)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:365)
	at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:240)
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:88)
	at

[Snip my code]

Caused by: javax.ws.rs.ProcessingException: java.lang.IllegalArgumentException: Error parsing media type ''
	at org.glassfish.jersey.message.internal.InboundMessageContext$5.apply(InboundMessageContext.java:455)
	at org.glassfish.jersey.message.internal.InboundMessageContext$5.apply(InboundMessageContext.java:449)
	at org.glassfish.jersey.message.internal.InboundMessageContext.singleHeader(InboundMessageContext.java:334)
	... 81 common frames omitted
Caused by: java.lang.IllegalArgumentException: Error parsing media type ''
	at org.glassfish.jersey.message.internal.MediaTypeProvider.fromString(MediaTypeProvider.java:69)
	at org.glassfish.jersey.message.internal.MediaTypeProvider.fromString(MediaTypeProvider.java:37)
	at javax.ws.rs.core.MediaType.valueOf(MediaType.java:172)
	at org.glassfish.jersey.message.internal.InboundMessageContext$5.apply(InboundMessageContext.java:453)
	... 83 common frames omitted
Caused by: java.text.ParseException: End of header.
	at org.glassfish.jersey.message.internal.HttpHeaderReaderImpl.getNextCharacter(HttpHeaderReaderImpl.java:155)
	at org.glassfish.jersey.message.internal.HttpHeaderReaderImpl.next(HttpHeaderReaderImpl.java:116)
	at org.glassfish.jersey.message.internal.HttpHeaderReaderImpl.next(HttpHeaderReaderImpl.java:111)
	at org.glassfish.jersey.message.internal.HttpHeaderReader.nextToken(HttpHeaderReader.java:105)
	at org.glassfish.jersey.message.internal.MediaTypeProvider.valueOf(MediaTypeProvider.java:87)
	at org.glassfish.jersey.message.internal.MediaTypeProvider.fromString(MediaTypeProvider.java:67)
	... 86 common frames omitted
```

**Comment by jansupol** [comment]
The problem seems to be that the server sends Content-Type that does not comply with [RFC 7231](https://tools.ietf.org/html/rfc7231#section-3.1.1.1). So basically this bug asks for any format that does not comply with the RFC to default to Application/Octet-Stream.

**Comment by jansupol** [comment]
I think a better solution than silently change the media type is to let the user tell Jersey that she is aware of handling the Content-Type that does not comply with the RFC and tell Jersey what should the expected media type be. That can be done using the HeaderDelegateProvider.

**Comment by jansupol** [comment]
Another solution for you seems to be using `ReaderInterceptor` which will change the ContentType Header.

**Comment by ewanmellor** [comment]
Why make it complicated?  application/octet-stream is a perfectly good fallback for broken / missing Content-Type headers.

When I call readEntity asking for an InputStream, I'm expecting you to read the entity and put it on my InputStream.  I'm not expecting you to barf out.  I'm certainly not expecting to have to inject a bunch of opaque interceptor code just to stop you barfing out.

**Comment by jansupol** [comment]
>Why make it complicated? application/octet-stream is a perfectly good fallback for broken / missing Content-Type headers.

Unfortunately, not. It might be a good fallback when you need to read the `InputStream`, but when you want to read for instance `String`, you would prefer "text/plain", for JSON, you would want to have "application/json". Section 4.2.4 of the JAX-RS Specification describes the media types for standard entity providers, for instance for `InputStream`, there is "*/*".
