### ISSUE TITLE
@Inject null into ExceptionMapper fails

### ISSUE THREAD

**Issue by namedgraph** [eclipse-ee4j/jersey#4440]
Hi,

again encountering an issue while upgrading from 1.19 to 2.30.1.

Injecting a `null` value using `@Context` hasn't been a problem, so now I'm attempting the same using `@Inject` (into `ExceptionMapper`).

However it seems that a proxy object is created for a `null` value, and it cannot be accessed. In my proper code I get this exception:
```
09-Apr-2020 12:50:19.310 SEVERE [http-nio-8080-exec-1] org.glassfish.jersey.server.ServerRuntime$Responder.mapException An exception has been thrown from an exception mapper class com.atomgraph.server.mapper.NotFoundExceptionMapper.
    java.lang.IllegalStateException: An instance for the descriptor org.glassfish.jersey.internal.inject.ForeignDescriptorImpl@b4 was already seeded in this scope. Old instance: null New instance: null
            at org.glassfish.jersey.internal.guava.Preconditions.checkState(Preconditions.java:193)
            at org.glassfish.jersey.inject.hk2.Hk2RequestScope$Instance.put(Hk2RequestScope.java:108)
            at org.glassfish.jersey.inject.hk2.RequestContext.findOrCreate(RequestContext.java:60)
            at org.jvnet.hk2.internal.MethodInterceptorImpl.internalInvoke(MethodInterceptorImpl.java:65)
            at org.jvnet.hk2.internal.MethodInterceptorImpl.invoke(MethodInterceptorImpl.java:101)
            at org.jvnet.hk2.internal.MethodInterceptorInvocationHandler.invoke(MethodInterceptorInvocationHandler.java:39)
            at com.sun.proxy.$Proxy38.getTemplate(Unknown Source)
            at com.atomgraph.server.mapper.ExceptionMapperBase.getResponseBuilder(ExceptionMapperBase.java:100)
            at com.atomgraph.server.mapper.NotFoundExceptionMapper.toResponse(NotFoundExceptionMapper.java:35)
            at com.atomgraph.server.mapper.NotFoundExceptionMapper.toResponse(NotFoundExceptionMapper.java:29)
            at org.glassfish.jersey.server.ServerRuntime$Responder.mapException(ServerRuntime.java:528)
            at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:403)
            at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261)
            at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
            at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
            at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
            at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
            at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
            at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
            at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
            at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
            at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
            at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
            at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
            at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
            at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
            at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
            at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
            at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
            at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
            at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
            at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
            at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
            at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
            at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
            at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
            at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
            at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
            at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
            at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
            at java.lang.Thread.run(Thread.java:748)
09-Apr-2020 12:50:19.314 SEVERE [http-nio-8080-exec-1] org.glassfish.jersey.server.ServerRuntime$Responder.mapException An exception was not mapped due to exception mapper failure. The HTTP 500 response will be returned.
    com.atomgraph.core.exception.NotFoundException: Resource has not matched any ldt:Template
            at com.atomgraph.server.model.impl.ResourceBase.getSubResource(ResourceBase.java:222)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.glassfish.jersey.server.internal.routing.SubResourceLocatorRouter.lambda$getResource$0(SubResourceLocatorRouter.java:132)
            at org.glassfish.jersey.server.internal.routing.SubResourceLocatorRouter.getResource(SubResourceLocatorRouter.java:150)
            at org.glassfish.jersey.server.internal.routing.SubResourceLocatorRouter.apply(SubResourceLocatorRouter.java:86)
            at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:86)
            at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89)
            at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89)
            at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89)
            at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89)
            at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:69)
            at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:38)
            at org.glassfish.jersey.process.internal.Stages.process(Stages.java:173)
            at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:245)
            at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
            at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
            at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
            at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
            at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
            at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
            at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
            at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
            at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
            at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
            at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
            at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
            at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
            at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
            at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
            at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
            at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
            at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
            at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
            at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
            at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
            at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
            at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
            at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
            at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
            at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
            at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
            at java.lang.Thread.run(Thread.java:748)
```
I have attempted it to reproduce it with this code:
https://github.com/namedgraph/jersey-exception-mapper-test/tree/master/src/main/java/jersey/test/mapper_injection

However here I get a different exception (maybe due to different servlet containers?):
```
Bal 09, 2020 2:51:13 PM org.glassfish.jersey.server.ServerRuntime$Responder mapException
SEVERE: An exception has been thrown from an exception mapper class jersey.test.mapper_injection.NotFoundExceptionMapper.
MultiException stack 1 of 1
java.lang.IllegalStateException: Proxiable context org.glassfish.jersey.inject.hk2.RequestContext@19deca81 findOrCreate returned a null for descriptor SystemDescriptor(
	implementation=jersey.test.mapper_injection.PerRequestInterfaceFactory
	contracts={jersey.test.mapper_injection.PerRequestInterface}
	scope=org.glassfish.jersey.process.internal.RequestScoped
	qualifiers={}
	descriptorType=PROVIDE_METHOD
	descriptorVisibility=NORMAL
	metadata=
	rank=0
	loader=org.glassfish.hk2.utilities.binding.AbstractBinder$2@7ad18a93
	proxiable=true
	proxyForSameScope=false
	analysisName=null
	id=142
	locatorId=0
	identityHashCode=516976368
	reified=true) and handle ServiceHandle(SystemDescriptor(
	implementation=jersey.test.mapper_injection.NotFoundExceptionMapper
	contracts={javax.ws.rs.ext.ExceptionMapper}
	scope=javax.inject.Singleton
	qualifiers={org.glassfish.jersey.internal.inject.Custom}
	descriptorType=CLASS
	descriptorVisibility=NORMAL
	metadata=
	rank=0
	loader=null
	proxiable=null
	proxyForSameScope=null
	analysisName=null
	id=149
	locatorId=0
	identityHashCode=1181055598
	reified=true),696269537)
	at org.jvnet.hk2.internal.MethodInterceptorImpl.internalInvoke(MethodInterceptorImpl.java:68)
	at org.jvnet.hk2.internal.MethodInterceptorImpl.invoke(MethodInterceptorImpl.java:101)
	at org.jvnet.hk2.internal.MethodInterceptorInvocationHandler.invoke(MethodInterceptorInvocationHandler.java:39)
	at com.sun.proxy.$Proxy35.getField(Unknown Source)
	at jersey.test.mapper_injection.NotFoundExceptionMapper.toResponse(NotFoundExceptionMapper.java:22)
	at jersey.test.mapper_injection.NotFoundExceptionMapper.toResponse(NotFoundExceptionMapper.java:13)
	at org.glassfish.jersey.server.ServerRuntime$Responder.mapException(ServerRuntime.java:528)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:403)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
```

If I debug the test code and inspect `obj.getField()` (where `obj` should be injected as null, but is instead a proxy object), I get the same exception as in my proper code:
```
Exception occurred in target VM: An instance for the descriptor org.glassfish.jersey.internal.inject.ForeignDescriptorImpl@8e was already seeded in this scope. Old instance: null New instance: null 
java.lang.IllegalStateException: An instance for the descriptor org.glassfish.jersey.internal.inject.ForeignDescriptorImpl@8e was already seeded in this scope. Old instance: null New instance: null
	at org.glassfish.jersey.internal.guava.Preconditions.checkState(Preconditions.java:193)
	at org.glassfish.jersey.inject.hk2.Hk2RequestScope$Instance.put(Hk2RequestScope.java:108)
	at org.glassfish.jersey.inject.hk2.RequestContext.findOrCreate(RequestContext.java:60)
	at org.jvnet.hk2.internal.MethodInterceptorImpl.internalInvoke(MethodInterceptorImpl.java:65)
	at org.jvnet.hk2.internal.MethodInterceptorImpl.invoke(MethodInterceptorImpl.java:101)
	at org.jvnet.hk2.internal.MethodInterceptorInvocationHandler.invoke(MethodInterceptorInvocationHandler.java:39)
	at com.sun.proxy.$Proxy35.getField(Unknown Source)
	at jersey.test.mapper_injection.NotFoundExceptionMapper.toResponse(NotFoundExceptionMapper.java:22)
	at jersey.test.mapper_injection.NotFoundExceptionMapper.toResponse(NotFoundExceptionMapper.java:13)
	at org.glassfish.jersey.server.ServerRuntime$Responder.mapException(ServerRuntime.java:528)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:403)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
```

Does it have to do with scopes? `@Inject` `null` into a resource seems to work fine.

**Comment by namedgraph** [comment]
Looks like a similar issue: https://stackoverflow.com/questions/32877526/how-do-i-utilize-supportsnullcreation-in-jersey

**Comment by namedgraph** [comment]
It looks like [`Hk2RequestContext`](https://github.com/eclipse-ee4j/jersey/blob/master/inject/hk2/src/main/java/org/glassfish/jersey/inject/hk2/Hk2RequestScope.java#L108) uses injectee value as a map key, and if there are multiple `null`s in a scope, it becomes a conflict. 

I would assume injecting `null`s would be a pretty common use case, but I haven't seen it documented nor advised against anywhere.

I think I manged to work around this by injecting `Optional<TemplateCall> opt` generic instead of plain `TemplateCall tc` and doing a `opt.isPresent()` check instead of `tc != null`.

I also got rid of proxies since `ExceptionMapper` shold now be registered as request-scoped:

    register(NotFoundExceptionMapper.class);

The factory binder looks like this:

        {
            @Override
            protected void configure()
            {
                bindFactory(TemplateCallProvider.class).to(new TypeLiteral<Optional<TemplateCall>>() {}).in(RequestScoped.class);
            }
        });

**Comment by jansupol** [comment]
I do not think that injecting nulls should be supported. The injection is driven towards CDI in Jakarta REST 4.0 and I do not think CDI allows that.

**Comment by namedgraph** [comment]
Fair enough, `Optional<>` can be used as a workaround.

But can we at least get a mention of this in the 1.x migration guide? This is one of the areas where the behavior changed substantially yet it is not mentioned anywhere (as far as I could see).

**Comment by namedgraph** [comment]
@jansupol how does one inject a proxiable `Optional<>` though?

I have

        register(new AbstractBinder()
        {
            @Override
            protected void configure()
            {
                bindFactory(new TemplatesFactory()).to(new TypeLiteral<Optional<Templates>>() {}).
                proxy(true).proxyForSameScope(false).
                in(RequestScoped.class);
            }
        });

and what I get is

```
MultiException stack 1 of 2
        java.lang.RuntimeException: java.util.Optional is final
                at javassist.util.proxy.ProxyFactory.checkClassAndSuperName(ProxyFactory.java:927)
                at javassist.util.proxy.ProxyFactory.makeSortedMethodList(ProxyFactory.java:951)
                at javassist.util.proxy.ProxyFactory.computeSignature(ProxyFactory.java:961)
                at javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:447)
                at org.jvnet.hk2.internal.ProxyUtilities$4.run(ProxyUtilities.java:148)
                at java.security.AccessController.doPrivileged(Native Method)
                at org.jvnet.hk2.internal.ProxyUtilities.secureCreate(ProxyUtilities.java:128)
                at org.jvnet.hk2.internal.ProxyUtilities.generateProxy(ProxyUtilities.java:194)
                at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2074)
                at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
                at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
                at org.jvnet.hk2.internal.OptionalActiveDescriptor.create(OptionalActiveDescriptor.java:100)
                at org.jvnet.hk2.internal.OptionalActiveDescriptor.create(OptionalActiveDescriptor.java:40)
                at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:46)
                at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
                at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:666)
                at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:54)
                at org.jvnet.hk2.internal.Utilities.justInject(Utilities.java:988)
                at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:998)
                at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:976)
                at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.inject(AbstractHk2InjectionManager.java:202)
```

**Comment by kemuri-9** [comment]
Rather than injecting null, there are mechanisms for having an injection be optional:
* a `javax.inject.Provider` of the service can be injected instead of the service directly. One feature of Provider is `lazy or optional retrieval of an instance`, so it can return null when there is no service available for the environment/circumstances.
In your example this would become `@Inject Provider<PerRequestInterface> obj`
* the `org.jvnet.hk2.annotations.Optional` annotation can be utilized which indicates to the hk2 injection engine that the injection is (as the name indicates) optional. So if no instance can be found within the system, no error is thrown and the annotated element is simply null.
In your example this would become `@Inject @Optional PerRequestInterface obj`

As the behaviors are a bit different, one should choose the more appropriate one for the desired scenario.
For scenarios where the parent service and child service are in the same scope, `@Optional` is the simplest route, and
For scenarios where the parent service and child services are in different scopes, such as a Singleton wanting RequestScoped data points, `Provider` generally has the most expected behavior.
