### ISSUE TITLE
ChunkedOutput race condition

### ISSUE THREAD

**Issue by yajirobee** [eclipse-ee4j/jersey#4493]
Hi, I faced following error when I use `ChunkedOutput` for a response. It happens rarely. 
I confirmed this happens with jersey 2.30.1 and jetty 9.4.27.v20200227.
```
ava.lang.IllegalStateException: s=OPEN,api=BLOCKED,sc=false,e=null
    at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:693)
    at org.glassfish.jersey.servlet.internal.ResponseWriter$NonCloseableOutputStreamWrapper.flush(ResponseWriter.java:306)
    at org.glassfish.jersey.message.internal.CommittingOutputStream.flush(CommittingOutputStream.java:263)
    at org.glassfish.jersey.message.internal.OutboundMessageContext.close(OutboundMessageContext.java:840)
    at org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:389)
    at org.glassfish.jersey.server.ChunkedOutput.flushQueue(ChunkedOutput.java:293)
    at org.glassfish.jersey.server.ChunkedOutput.setContext(ChunkedOutput.java:374)
    at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:687)
    at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:371)
    at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:361)
    at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256)
...
```

It seems `ContainerResponse#close` is called outside of synchronized.
https://github.com/eclipse-ee4j/jersey/blob/4f7c616f3484b01c249eca9fcadf378f4f3eb5f4/core-server/src/main/java/org/glassfish/jersey/server/ChunkedOutput.java#L293
I suspect the error happens when `ContainerResponse#close` is called while another thread is calling `write`.

**Comment by jansupol** [comment]
See [related](https://github.com/eclipse/jetty.project/issues/4461)

**Comment by jansupol** [comment]
It's the `HttpOutput` which is synchronized. To me, it looks like the state changes from BLOCKING to BLOCKED, but not back in its synchronized block.

**Comment by jansupol** [comment]
`HttpOutput` really does not look thread safe, but it uses a bunch of synchronized blocks, which is confusing. I did not find any requirement on `ServletOutputStream` to be thread safe.
