### ISSUE TITLE
SocketInputStream.socketRead0 - hangs while client sending request to server

### ISSUE THREAD

**Issue by arturro1991** [eclipse-ee4j/jersey#4517]
Im using javax.ws.rs.client to send a request to a web service and once in a while we get the thread hangs and we have to restart the process.

Im familiar with few jdk bugs fixed and we are using jre 8 251 that should contain fixes to similar problems ive found.

We are using javax.ws.rs-api-2.1,jersey-client-2.26. Let me know if other dependencies needed.

Any ideas how to solve the issue in the below stack trace?

"pool-1-thread-1" #22 prio=5 os_prio=0 tid=0x000000001979b800 nid=0x1ae4 runnable [0x000000001ad7e000]
   java.lang.Thread.State: RUNNABLE
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(Unknown Source)
    at java.net.SocketInputStream.read(Unknown Source)
    at java.net.SocketInputStream.read(Unknown Source)
    at sun.security.ssl.InputRecord.readFully(Unknown Source)
    at sun.security.ssl.InputRecord.read(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
    - locked <0x00000000c05df118> (a java.lang.Object)
    at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
    at sun.security.ssl.AppInputStream.read(Unknown Source)
    - locked <0x00000000c05e11a0> (a sun.security.ssl.AppInputStream)
    at java.io.BufferedInputStream.fill(Unknown Source)
    at java.io.BufferedInputStream.read1(Unknown Source)
    at java.io.BufferedInputStream.read(Unknown Source)
    - locked <0x00000000c05e11b8> (a java.io.BufferedInputStream)
    at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
    at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
    - locked <0x00000000c05e1210> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    - locked <0x00000000c05e1210> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
    at java.net.HttpURLConnection.getResponseCode(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
    at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:390)
    at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:282)
    at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278)
    at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:753)
    at org.glassfish.jersey.client.JerseyInvocation$$Lambda$89/1655661149.call(Unknown Source)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:752)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:445)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:351)

    at my code executing a request to web service

    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
java glassfish jax-rs jersey-client

**Comment by jansupol** [comment]
From the Stacktrace, it looks like the connection is open, but the server does not send data. A reproducer (at least some that fails in 1 of 1000 cases) would be nice.

**Comment by arturro1991** [comment]
> From the Stacktrace, it looks like the connection is open, but the server does not send data. A reproducer (at least some that fails in 1 of 1000 cases) would be nice.

Unfortunately we do not know how to reproduce it.
This product runs the same way for 5 years and we never heard our customers complaining on this.
For specific customer and his environment it happens at least once every few weeks. The request executed every 5 minutes for about 180 times with different parameters.

Initially we did not closed the response on the client side (it worked this way for 5 years) but after I fixed that I expected this issue to be solved but it still was not resolved.

**Comment by jansupol** [comment]
This is hard to say why the code starts to do this. It could be a deadlock somewhere. Do you happen to have another thread blocked as well?

**Comment by arturro1991** [comment]
I will try to find one but I assume it will be exactly the same stack trace - it always happens on this particular request - this request called about 180 times every 5 minutes.

**Comment by jansupol** [comment]
I mean for a different thread - in case it would be a deadlock, you need to have 2 threads, both blocked.

**Comment by jansupol** [comment]
Related [SO](https://stackoverflow.com/questions/62444807/socketinputstream-socketread0-hangs-while-client-sending-request-to-server-usi) bug.

**Comment by arturro1991** [comment]
I don't think that this is a dead lock case - the pool is in size of 1 - only 1 thread executes this task.
Also this is the only request the client performs in this process :-(

**Comment by jansupol** [comment]
Do you use the client within a server resource method?

**Comment by arturro1991** [comment]
No. This is thread object using using sleep for 5 mins and after it wakes up he executes this request. This thread lunched from the main method when the service starts and there is no other interaction with this thread.

**Comment by jbescos** [comment]
It could be the server is hanged. It is a good idea to set timeouts to avoid sockets to hang forever, so you will not need to restart the process.
```
    client.property(ClientProperties.CONNECT_TIMEOUT, 10000);
    client.property(ClientProperties.READ_TIMEOUT,    10000);
```

**Comment by jansupol** [comment]
Possibly, you might have run out of threads. You can try to utilize `http.maxConnections` and `keep.alive` property that increases the default thread pool size. Optionally, you can try [ApacheConnectorProvider](https://eclipse-ee4j.github.io/jersey.github.io/apidocs/snapshot/jersey/org/glassfish/jersey/apache/connector/ApacheConnectorProvider.html) that supports better pooling  via its `PoolingHttpClientConnectionManager`.
