### ISSUE TITLE
NoSuchElementException occasionally thrown when using PostInvocationInterceptor

### ISSUE THREAD

**Issue by docent** [eclipse-ee4j/jersey#4544]
Using Jersey 2.30.1, after adding a PosInvocationInterceptor, I occasionally see the following exception. I believe I am not doing anything non-standard. Looks like a race/threading issue possibly?

Caused by: java.util.NoSuchElementException
	at java.util.ArrayList$Itr.next(ArrayList.java:862)
	at org.glassfish.jersey.client.InvocationInterceptorStages$PostInvocationInterceptorStage.afterRequestWithException(InvocationInterceptorStages.java:200)
	at org.glassfish.jersey.client.InvocationInterceptorStages$PostInvocationInterceptorStage.afterRequest(InvocationInterceptorStages.java:244)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:307)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:623)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)

**Comment by jansupol** [comment]
There was a significant bug in 2.30.1 in the PostInvocationInterceptor. Can you please try with 2.31?
