### ISSUE TITLE
Jersey HK2 support for Graalvm native image

### ISSUE THREAD

**Issue by bajajyog** [eclipse-ee4j/jersey#4547]
I am trying to build Spring Boot Jersey micro service graalvm native image. I am getting error while image running for Jersey HK2 proxy. Does Jersey support graalvm native image?. Please advise. I also opened issue with Graalvm team.

Error stack:-

java.lang.IllegalStateException: A descriptor SystemDescriptor(
	implementation=org.glassfish.jersey.inject.hk2.SupplierFactoryBridge
	contracts={javax.ws.rs.core.UriInfo,org.glassfish.jersey.server.ExtendedUriInfo,javax.ws.rs.container.ResourceInfo}
	scope=org.glassfish.jersey.process.internal.RequestScoped
	qualifiers={}
	descriptorType=PROVIDE_METHOD
	descriptorVisibility=NORMAL
	metadata=
	rank=0
	loader=org.glassfish.hk2.utilities.binding.AbstractBinder$2@12e53dc60
	proxiable=true
	proxyForSameScope=false
	analysisName=null
	id=54
	locatorId=0
	identityHashCode=694413299
	reified=true) requires a proxy, but the proxyable library is not on the classpath
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2071) ~[?:?]
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93) ~[?:?]
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67) ~[?:?]
	at org.glassfish.jersey.inject.hk2.ContextInjectionResolverImpl.resolve(ContextInjectionResolverImpl.java:103) ~[omsai:?]
	at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:188) ~[?:?]
	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:211) ~[?:?]
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:334) ~[?:?]
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463) ~[?:?]
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59) ~[?:?]
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47) ~[?:?]
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131) ~[?:?]
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176) ~[?:?]
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98) ~[?:?]
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102) ~[?:?]
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93) ~[?:?]
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67) ~[?:?]
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.lambda$getAllServiceHolders$0(AbstractHk2InjectionManager.java:136) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:?]
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:?]
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllServiceHolders(AbstractHk2InjectionManager.java:140) ~[?:?]
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllServiceHolders(ImmediateHk2InjectionManager.java:30) ~[?:?]
	at org.glassfish.jersey.internal.inject.Providers.getServiceHolders(Providers.java:307) ~[?:?]
	at org.glassfish.jersey.internal.inject.Providers.getCustomProviders(Providers.java:151) ~[?:?]
	at org.glassfish.jersey.message.internal.MessageBodyFactory.initialize(MessageBodyFactory.java:219) ~[?:?]
	at org.glassfish.jersey.message.internal.MessageBodyFactory$MessageBodyWorkersConfigurator.postInit(MessageBodyFactory.java:114) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$2(ApplicationHandler.java:349) ~[?:?]
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:349) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:293) ~[?:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[?:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[?:?]
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:292) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259) ~[?:?]
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311) ~[?:?]
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154) ~[?:?]
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:347) ~[?:?]
	at javax.servlet.GenericServlet.init(GenericServlet.java:158) ~[omsai:?]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1134) ~[?:?]
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:986) ~[?:?]
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedContext.load(TomcatEmbeddedContext.java:82) ~[omsai:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[?:?]
	at java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2897) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:?]
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedContext.lambda$deferredLoadOnStartup$0(TomcatEmbeddedContext.java:65) ~[omsai:?]
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedContext.doWithThreadContextClassLoader(TomcatEmbeddedContext.java:106) ~[omsai:?]
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedContext.deferredLoadOnStartup(TomcatEmbeddedContext.java:64) ~[omsai:?]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.performDeferredLoadOnStartup(TomcatWebServer.java:305) ~[omsai:?]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:216) ~[omsai:?]
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43) ~[?:?]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[omsai:?]

**Comment by jansupol** [comment]
Provided in 2.35 by #4803 #4800. See the [Doc](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/graalvm-native-image.html), too.
