### ISSUE TITLE
jakarta.ws.rs.ProcessingException: java.net.SocketTimeoutException on valid oracle web page

### ISSUE THREAD

**Issue by oliviercailloux** [eclipse-ee4j/jersey#4673]
The code `ClientBuilder.newBuilder().connectTimeout(10, TimeUnit.SECONDS).readTimeout(10, TimeUnit.SECONDS).build().target("https://www.oracle.com/java/technologies/naming-conventions.html").request().get();` throws a “Read timed out” exception, even though this web page answers GET requests (as checked, on the same computer, using a web browser and using `curl --http1.1 -I -v https://www.oracle.com/java/technologies/naming-conventions.html`).

Here is the full stack trace.
> javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
> 	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:261)
> 	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:297)
> 	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:619)
> 	at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:654)
> 	at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:648)
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
> 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
> 	at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:648)
> 	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:618)
> 	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:397)
> 	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:297)
> 	at io.github.oliviercailloux.check_links_from_source.MyTests.testOracle(MyTests.java:86)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
> 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
> 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
> 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
> 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
> 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
> 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
> 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
> 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
> 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
> 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
> 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
> 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
> 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
> 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
> 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
> 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
> 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
> 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
> 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
> 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
> 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
> 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
> 	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
> 	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
> 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
> 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:141)
> 	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
> 	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
> Caused by: java.net.SocketTimeoutException: Read timed out
> 	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
> 	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
> 	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
> 	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
> 	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:476)
> 	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:470)
> 	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
> 	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1354)
> 	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:963)
> 	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
> 	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
> 	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
> 	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:754)
> 	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1615)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
> 	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
> 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
> 	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:374)
> 	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:259)
> 	... 78 more

I use openjdk 11.0.9.1 2020-11-04 (the Debian stable default version).

**Comment by jansupol** [comment]
This seems to be because Oracle website is HTTPS only. Please see [the doc](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/client.html#d0e5317) about secure clients. You can also check our HTTPS [example](https://github.com/eclipse-ee4j/jersey/tree/master/examples/https-clientserver-grizzly).

**Comment by oliviercailloux** [comment]
> This seems to be because Oracle website is HTTPS only. 

Thank you for your reply. 

I realize I can’t find in the documentation how the client is supposed to behave by default, that is, when I do not explicitly set an SSLContext. The documentation is very scarce on that subject (unless I missed something).

* The JAX-RS standard does not mention anything at all about the HTTPS scheme or TLS or SSL encryption, neither in the [Jakarta RESTful Web Services](https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html) document, nor in the JSR 370 (JAX-RS 2.1, Final) document.
* The [Jersey documentation](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/client.html#d0e5317) does indicate how to configure a specific SSL context, but does not indicate how the client will behave when that is not done.

I expected that a JAX-RS client would, by default, try to connect using simple HTTP when given an http URL, and using the standard TLS-over-HTTP protocol when given an https URL, using the [`default`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/javax/net/ssl/SSLContext.html#getDefault()) `SSLContext` (which I can’t find documentation about but I assume does something reasonable boiling down to accepting oracle’s certificate and connecting seamlessly). 

But I understand from your answer that, on the contrary, in my example, the client tries to connect using simple HTTP even though it is given the URL `https://www.oracle.com/java/technologies/naming-conventions.html`. Do I understand correctly? If so, isn’t this quite unexpected and possibly insecure?

Sorry if I missed anything obvious…

**Comment by oliviercailloux** [comment]
Oops, forgot to mention the Javadoc JAX-RS.

* [`ClientBuilder#trustStore​`](https://javadoc.io/static/jakarta.ws.rs/jakarta.ws.rs-api/3.0.0/jakarta/ws/rs/client/ClientBuilder.html#trustStore(java.security.KeyStore)) indicates: “In case a custom trust store or custom SSL context is not specified, the trust management will be configured to use the default Java runtime settings.”
* [`ClientBuilder#sslContext`](https://javadoc.io/static/jakarta.ws.rs/jakarta.ws.rs-api/3.0.0/jakarta/ws/rs/client/ClientBuilder.html#sslContext(javax.net.ssl.SSLContext)) indicates: “Set the SSL context that will be used when creating secured transport connections to server endpoints from web targets created by the client instance that is using this SSL context.” Unfortunately, it does not further specify when exactly is the client supposed to create “secured transport connections”. I thought it was fair to assume that this is exactly in cases mandated by the scheme used (ftps VS https, …). But I may be wrong.
* [`Client#getSslContext()`](https://javadoc.io/static/jakarta.ws.rs/jakarta.ws.rs-api/3.0.0/jakarta/ws/rs/client/Client.html#getSslContext()) unfortunately leaves it unspecified (in my understanding) what exactly should be returned by default, that is, when the ClientBuilder was not given an explicit ssl context.

If my reading of the spec is correct, the client should try to connect to oracle, in my example, using standard TLS-over-HTTPS, in which case it is unclear to me why the call fails.

**Comment by oliviercailloux** [comment]
I guess this issue has become: How should (and does) Jersey behave with https connection attempts by default, i.e., when SSL / TLS are not configured explicitly?

Should I consider this a different issue and open a new one?

**Comment by chkal** [comment]
> This seems to be because Oracle website is HTTPS only. Please see [the doc](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/client.html#d0e5317) about secure clients. You can also check our HTTPS [example](https://github.com/eclipse-ee4j/jersey/tree/master/examples/https-clientserver-grizzly).

@jansupol I don't fully understand. Even if the server enforces TLS, why does the client run into a timeout?

**Comment by oliviercailloux** [comment]
Shouldn’t this problem be devoted more attention? Currently, Jersey fails to execute a basic GET to a valid web page. Isn’t this an important problem? This issue is opened since four months and has received only a one line “explanation” that does not seem understandable to me or to @chkal.

**Comment by jansupol** [comment]
So this gets weird.

**Comment by jbescos** [comment]
With curl this also gets stuck:
`curl --noproxy "*" --http1.1 -H "User-Agent: Jersey/4.5.0" https://www.oracle.com/java/technologies/naming-conventions.html`

but if we remove the http1.1, it uses http 2, and it works:
`curl --noproxy "*" -H "User-Agent: Jersey/4.5.0" https://www.oracle.com/java/technologies/naming-conventions.html`

So the problem happens when user-agent is sent as Jersey/number and using http1.1

This looks a bug in www.oracle.com

**Comment by oliviercailloux** [comment]
Very weird. If anyone reading this knows someone at Oracle, please drop them an e-mail about this. In the meantime, I suppose I will change the user agent to work around the problem.

**Comment by oliviercailloux** [comment]
Interestingly enough, `curl --http1.1 -H "User-Agent: Jersey/4.5.0" https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/net/class-use/URL.html` does not fall under Oracle’s dislike for Jersey.

**Comment by oliviercailloux** [comment]
I just tried to write to webmaster<span>@</span>oracle.com, just in case, but got an “Undeliverable” reply (“webmaster wasn't found at oracle.com”). Here is the message, in case someone can make it reach an appropriate person.

Dear Webmaster,

The www<span>.</span>oracle.com website fails to answer, and times out, when contacted through HTTP1.1 with User agent Jersey/4.5.0. For example, `curl --http1.1 -H "User-Agent: Jersey/4.5.0" https://www.oracle.com/java/technologies/jaxp-introduction.html` triggers the problem.

See https://github.com/eclipse-ee4j/jersey/issues/4673.

Could you please investigate this and report there?

**Comment by jansupol** [comment]
An Oracle internal bug is opened and waiting for a resolution.
