### ISSUE TITLE
ClassCastException in FormDataParamValueParamProvider

### ISSUE THREAD

**Issue by vavrajosef** [eclipse-ee4j/jersey#4761]
Hi,
I have app that accepts multipart/mixed POST request, but I am getting ClassCastException.
`java.lang.ClassCastException: class org.glassfish.jersey.media.multipart.MultiPart cannot be cast to class org.glassfish.jersey.media.multipart.FormDataMultiPart (org.glassfish.jersey.media.multipart.MultiPart and org.glassfish.jersey.media.multipart.FormDataMultiPart are in unnamed module of loader 'app')`

This seems to be cause lines 271 and 279 in FormDataParamValueParamProvider.

On line 271 there is:
`entity = request.readEntity(FormDataMultiPart.class);`
which assigns object of type Multipart and then on line 279:
`return (FormDataMultiPart)entity;`
ClassCastException is thrown. 

I am not really sure if I did anything incorrectly, because noone seems to experience this issue.

**Comment by jansupol** [comment]
There seems to be the following code:
```
final String requestPropertyName = FormDataMultiPart.class.getName()
Object entity = request.getProperty(requestPropertyName);
if (entity == null) { //entity not null in your case
   ....
}
return (FormDataMultiPart) entity;
```
So the question is what is the property `request.getProperty(requestPropertyName)`.

A reproducer would help. Also please report the Jersey version and the stack trace.

**Comment by vavrajosef** [comment]
jersey version is 2.32

`request.getProperty(requestPropertyName)`
returns null

And here is stacktrace:

```
java.lang.ClassCastException: class org.glassfish.jersey.media.multipart.MultiPart cannot be cast to class org.glassfish.jersey.media.multipart.FormDataMultiPart (org.glassfish.jersey.media.multipart.MultiPart and org.glassfish.jersey.media.multipart.FormDataMultiPart are in unnamed module of loader 'app')
	at org.glassfish.jersey.media.multipart.internal.FormDataParamValueParamProvider$ValueProvider.getEntity(FormDataParamValueParamProvider.java:91)
	at org.glassfish.jersey.media.multipart.internal.FormDataParamValueParamProvider$FormDataParamValueProvider.apply(FormDataParamValueParamProvider.java:235)
	at org.glassfish.jersey.media.multipart.internal.FormDataParamValueParamProvider$FormDataParamValueProvider.apply(FormDataParamValueParamProvider.java:222)
	at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.apply(ParamValueFactoryWithSource.java:50)
	at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:64)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:109)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
```

Thanks for looking into this.

**Comment by jbescos** [comment]
@vavrajosef  I am trying to reproduce this. That request.getProperty(requestPropertyName) is obtained from a request attribute of the web container, so it is relevant to know in which web container is happening.

It looks the request attribute for the name 'org.glassfish.jersey.media.multipart.FormDataMultiPart' contains an unexpected value.

Do you know were is it deployed your application to debug this further?, Tomcat, Jetty, Grizzly, etc?.
