### ISSUE TITLE
Documentation on how to use Jersey client inside OSGi framework

### ISSUE THREAD

**Issue by vxmn** [eclipse-ee4j/jersey#4910]
Is there any documentation on how to use Jersey client 3.0.3 inside an OSGi framework?

When using ClientBuilder.newBuilder(), I get a ClassNotFoundException. This is not surprising, since the classloader of jakarta.ws.rs.client.ClientBuilder does not know about the Jersey implementation. 

```
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Provider for jakarta.ws.rs.client.ClientBuilder cannot be found
	at jakarta.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:77)
	at ...
Caused by: java.lang.ClassNotFoundException: Provider for jakarta.ws.rs.client.ClientBuilder cannot be found
	at jakarta.ws.rs.client.FactoryFinder.find(FactoryFinder.java:168)
	at jakarta.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:62)
	... 31 more
```

However I also load osgi-resource-locator bundle. The debug entries suggest, that it picks up on the jersey client.
```
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = ch.qos.logback.classic [1], serviceName = javax.servlet.ServletContainerInitializer, providerNames = [ch.qos.logback.classic.servlet.LogbackServletContainerInitializer]
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = com.sun.xml.bind.jaxb-osgi [29], serviceName = com.sun.tools.xjc.Plugin, providerNames = [com.sun.tools.xjc.addon.code_injector.PluginImpl, com.sun.tools.xjc.addon.locator.SourceLocationAddOn, com.sun.tools.xjc.addon.sync.SynchronizedMethodAddOn, com.sun.tools.xjc.addon.at_generated.PluginImpl, com.sun.tools.xjc.addon.episode.PluginImpl, com.sun.tools.xjc.addon.accessors.PluginImpl]
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = com.sun.xml.bind.jaxb-osgi [29], serviceName = javax.xml.bind.JAXBContext, providerNames = [com.sun.xml.bind.v2.ContextFactory]
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = com.sun.xml.bind.jaxb-osgi [29], serviceName = javax.xml.bind.JAXBContextFactory, providerNames = [com.sun.xml.bind.v2.JAXBContextFactory]
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = org.hibernate.validator [73], serviceName = javax.validation.spi.ValidationProvider, providerNames = [org.hibernate.validator.HibernateValidator]
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = io.netty.common [80], serviceName = reactor.blockhound.integration.BlockHoundIntegration, providerNames = [io.netty.util.internal.Hidden$NettyBlockHoundIntegration]
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = org.apache.felix.http.jetty [85], serviceName = javax.servlet.ServletContainerInitializer, providerNames = [org.eclipse.jetty.websocket.server.NativeWebSocketServletContainerInitializer]
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = org.apache.felix.http.jetty [85], serviceName = org.eclipse.jetty.http.HttpFieldPreEncoder, providerNames = [org.eclipse.jetty.http.Http1FieldPreEncoder, org.eclipse.jetty.http2.hpack.HpackFieldPreEncoder]
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = org.apache.felix.http.jetty [85], serviceName = 
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = com.fasterxml.jackson.core.jackson-core [95], serviceName = com.fasterxml.jackson.core.JsonFactory, providerNames = [com.fasterxml.jackson.core.JsonFactory]
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = com.fasterxml.jackson.core.jackson-databind [96], serviceName = com.fasterxml.jackson.core.ObjectCodec, providerNames = [com.fasterxml.jackson.databind.ObjectMapper]
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = com.fasterxml.jackson.module.jackson-module-jaxb-annotations [97], serviceName = com.fasterxml.jackson.databind.Module, providerNames = [com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule]
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = org.glassfish.jersey.core.jersey-client [105], serviceName = jakarta.ws.rs.client.ClientBuilder, providerNames = [org.glassfish.jersey.client.JerseyClientBuilder]
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = org.glassfish.jersey.core.jersey-common [106], serviceName = jakarta.ws.rs.ext.RuntimeDelegate, providerNames = [org.glassfish.jersey.internal.RuntimeDelegateImpl]
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = org.glassfish.jersey.core.jersey-common [106], serviceName = org.glassfish.jersey.internal.spi.AutoDiscoverable, providerNames = [org.glassfish.jersey.logging.LoggingFeatureAutoDiscoverable, org.glassfish.jersey.internal.config.ExternalPropertiesAutoDiscoverable]
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = org.glassfish.jersey.core.jersey-server [107], serviceName = jakarta.ws.rs.ext.RuntimeDelegate, providerNames = [org.glassfish.jersey.server.internal.RuntimeDelegateImpl]
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = org.glassfish.jersey.core.jersey-server [107], serviceName = org.glassfish.jersey.internal.spi.AutoDiscoverable, providerNames = [org.glassfish.jersey.server.filter.internal.ServerFiltersAutoDiscoverable]
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = org.glassfish.jersey.core.jersey-server [107], serviceName = org.glassfish.jersey.internal.spi.ForcedAutoDiscoverable, providerNames = [org.glassfish.jersey.server.wadl.internal.WadlAutoDiscoverable, org.glassfish.jersey.server.internal.monitoring.MonitoringAutodiscoverable]
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = org.glassfish.jersey.core.jersey-server [107], serviceName = org.glassfish.jersey.model.internal.spi.ParameterServiceProvider, providerNames = [org.glassfish.jersey.server.model.Parameter$ServerParameterService]
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = org.glassfish.jersey.ext.jersey-bean-validation [108], serviceName = org.glassfish.jersey.internal.spi.ForcedAutoDiscoverable, providerNames = [org.glassfish.jersey.server.validation.internal.ValidationAutoDiscoverable]
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = org.glassfish.jersey.media.jersey-media-jaxb [110], serviceName = org.glassfish.jersey.internal.spi.ForcedAutoDiscoverable, providerNames = [org.glassfish.jersey.jaxb.internal.JaxbAutoDiscoverable]
org.glassfish.hk2.osgiresourcelocator:DEBUG: Bundle = org.glassfish.jersey.media.jersey-media-json-jackson [111], serviceName = org.glassfish.jersey.internal.spi.AutoDiscoverable, providerNames = [org.glassfish.jersey.jackson.internal.JacksonAutoDiscoverable]
```

When I try to get an instance of the JerseyClientBuilder from the ServiceLoader with `
ServiceLoader.lookupProviderInstances(ClientBuilder.class)`, I get a builder but this one fails to find RuntimeDelegate. 

```
java.lang.RuntimeException: java.lang.ClassNotFoundException: Provider for jakarta.ws.rs.ext.RuntimeDelegate cannot be found
	at jakarta.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:113)
	at jakarta.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:84)
	at jakarta.ws.rs.core.UriBuilder.newInstance(UriBuilder.java:69)
	at jakarta.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:91)
	at org.glassfish.jersey.client.JerseyWebTarget.<init>(JerseyWebTarget.java:50)
	at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:274)
	at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:56)
	at ...
	... 23 more
Caused by: java.lang.ClassNotFoundException: Provider for jakarta.ws.rs.ext.RuntimeDelegate cannot be found
	at jakarta.ws.rs.ext.FactoryFinder.find(FactoryFinder.java:168)
	at jakarta.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:98)
	... 38 more
```

Also, Jersey does not seem to register any OSGi services. Is there a sample project that uses Jersey 3.0.3 in an OSGi context?

**Comment by senivam** [comment]
We have examples for 3.0.3 here (including OSGi): https://github.com/eclipse-ee4j/jersey/tree/3.0.3/examples
And a chapter about OSGi for Jersey 3.0.3 here: https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest3x/deployment.html#osgi.shell

**Comment by vxmn** [comment]
Thanks for the hint. The project jersey-tests-osgi-function pointed me to the right direction: I needed to set the following system properties:

```
jakarta.ws.rs.ext.RuntimeDelegate=org.glassfish.jersey.internal.RuntimeDelegateImpl
jakarta.ws.rs.client.ClientBuilder=org.glassfish.jersey.client.JerseyClientBuilder
```
