### ISSUE TITLE
InboundMessageContext.getLength() blows up for CONTENT_LENGTH that exceed Integer limits

### ISSUE THREAD

**Issue by lalitmathwani** [eclipse-ee4j/jersey#4984]
We have a use case where we are using the jersey client (@ 2.33 currently) to issue a Http HEAD to an endpoint that hosts files for download.
For files sizes that exceed a threshold of 2 Gigs approx - the maximum Integer limit (2147483647) - we start to see NumberFormatExceptions. 

This issue seems to occur during the CONTENT_LENGTH parsing here  :
https://github.com/eclipse-ee4j/jersey/blob/9bb2e8dffe2ee307dde151b35f3b98fc81782d4c/core-common/src/main/java/org/glassfish/jersey/message/internal/InboundMessageContext.java#L435

Caused by: java.lang.NumberFormatException: For input string: \"4294967296\"\n\t
at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)\n\t
at java.base/java.lang.Integer.parseInt(Unknown Source)\n\t
at java.base/java.lang.Integer.parseInt(Unknown Source)\n\t
at org.glassfish.jersey.message.internal.InboundMessageContext$4.apply(InboundMessageContext.java:435)\n\t... 34 common frames omitted\n"

Checking if there a reason why the CONTENT_LENGTH values were constrained to Integers instead of Longs..

**Comment by jansupol** [comment]
HTTP RFC does not have a limit, browsers [do](https://www.motobit.com/help/scptutl/pa98.htm), Servlet [can use longs](https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletRequest.html#getContentLengthLong--) since 3.1.

Can Jersey use an additional method (getLengthLong)?

**Comment by jbescos** [comment]
> HTTP RFC does not have a limit, browsers [do](https://www.motobit.com/help/scptutl/pa98.htm), Servlet [can use longs](https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletRequest.html#getContentLengthLong--) since 3.1.
> 
> Can Jersey use an additional method (getLengthLong)?

I'm going to check this

**Comment by jbescos** [comment]
Adding stacktrace to see how to reproduce the issue.

It happens when javax.ws.rs.core.Response#getLength is invoked in user code. It looks Jersey is not invoking this method.

At the end, that is a method of the API. We could add a new method to return the getLength long, but then the user code will need to cast` javax.ws.rs.core.Response` to `InboundMessageContext`. Then call that new method. Does it make sense to do this?.

I also tried to send a big file, and I run into memory heap exceptions before having that NumberFormatException.

```
Thread [main] (Suspended (breakpoint at line 435 in InboundMessageContext$4))	
	InboundMessageContext$4.apply(String) line: 435	
	InboundMessageContext$4.apply(Object) line: 431	
	ClientResponse(InboundMessageContext).singleHeader(String, Function<String,T>, boolean) line: 335	
	ClientResponse(InboundMessageContext).getLength() line: 431	
	InboundJaxrsResponse.getLength() line: 177	
	AbortResponseClientTest.testRequestAbort() line: 112	
	NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
	NativeMethodAccessorImpl.invoke(Object, Object[]) line: 62	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
	Method.invoke(Object, Object...) line: 566	
	FrameworkMethod$1.runReflectiveCall() line: 59	
	FrameworkMethod$1(ReflectiveCallable).run() line: 12	
	FrameworkMethod.invokeExplosively(Object, Object...) line: 56	
	InvokeMethod.evaluate() line: 17	
	RunBefores.evaluate() line: 26	
	RunAfters.evaluate() line: 27	
	ParentRunner$3.evaluate() line: 306	
	BlockJUnit4ClassRunner$1.evaluate() line: 100	
	JUnit4(ParentRunner<T>).runLeaf(Statement, Description, RunNotifier) line: 366	
	JUnit4(BlockJUnit4ClassRunner).runChild(FrameworkMethod, RunNotifier) line: 103	
	JUnit4(BlockJUnit4ClassRunner).runChild(Object, RunNotifier) line: 63	
	ParentRunner$4.run() line: 331	
	ParentRunner$1.schedule(Runnable) line: 79	
	JUnit4(ParentRunner<T>).runChildren(RunNotifier) line: 329	
	ParentRunner<T>.access$100(ParentRunner, RunNotifier) line: 66	
	ParentRunner$2.evaluate() line: 293	
	ParentRunner$3.evaluate() line: 306	
	JUnit4(ParentRunner<T>).run(RunNotifier) line: 413	
	JUnit4Provider.execute(Class<?>, Notifier, Filter) line: 364	
	JUnit4Provider.executeWithRerun(Class<?>, Notifier) line: 272	
	JUnit4Provider.executeTestSet(Class<?>, RunListener, Notifier) line: 237	
	JUnit4Provider.invoke(Object) line: 158	
	ForkedBooter.runSuitesInProcess() line: 428	
	ForkedBooter.execute() line: 162	
	ForkedBooter.run(ForkedBooter, String[]) line: 562	
	ForkedBooter.main(String[]) line: 548	
```
