### ISSUE TITLE
Support for Java 11 Migration Issue

### ISSUE THREAD

**Issue by kumarvinothjoseph** [eclipse-ee4j/jersey#5005]
Java 11 + Tomcat 9 + 
<dependency>
	<groupId>com.sun.jersey</groupId>
	<artifactId>jersey-server</artifactId>
	<version>1.19.4</version>
</dependency>

org.apache.catalina.core.ApplicationContext.log Servlet.init() for servlet [jersey-serlvet] threw exception
	java.lang.IllegalArgumentException
		at jersey.repackaged.org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
		at jersey.repackaged.org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
		at jersey.repackaged.org.objectweb.asm.ClassReader.<init>(ClassReader.java:424)
		at com.sun.jersey.spi.scanning.AnnotationScannerListener.onProcess(AnnotationScannerListener.java:138)
		at com.sun.jersey.core.spi.scanning.uri.FileSchemeScanner$1.f(FileSchemeScanner.java:86)
		at com.sun.jersey.core.util.Closing.f(Closing.java:71)
		at com.sun.jersey.core.spi.scanning.uri.FileSchemeScanner.scanDirectory(FileSchemeScanner.java:83)
		at com.sun.jersey.core.spi.scanning.uri.FileSchemeScanner.scanDirectory(FileSchemeScanner.java:80)
		at com.sun.jersey.core.spi.scanning.uri.FileSchemeScanner.scan(FileSchemeScanner.java:71)
		at com.sun.jersey.core.spi.scanning.PackageNamesScanner.scan(PackageNamesScanner.java:226)
		at com.sun.jersey.core.spi.scanning.PackageNamesScanner.scan(PackageNamesScanner.java:142)
		at com.sun.jersey.api.core.ScanningResourceConfig.init(ScanningResourceConfig.java:80)
		at com.sun.jersey.api.core.PackagesResourceConfig.init(PackagesResourceConfig.java:104)
		at com.sun.jersey.api.core.PackagesResourceConfig.<init>(PackagesResourceConfig.java:78)
		at com.sun.jersey.api.core.PackagesResourceConfig.<init>(PackagesResourceConfig.java:89)
		at com.sun.jersey.spi.container.servlet.WebComponent.createResourceConfig(WebComponent.java:696)
		at com.sun.jersey.spi.container.servlet.WebComponent.createResourceConfig(WebComponent.java:674)
		at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:205)
		at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:394)
		at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:577)
		at javax.servlet.GenericServlet.init(GenericServlet.java:158)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1134)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1089)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:761)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:135)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:666)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by jansupol** [comment]
Jersey 1 will never be working with JDK 11. Jersey 2 is required, sorry.

**Comment by kumarvinothjoseph** [comment]
I dont see version 2 in maven dependency . 
https://mvnrepository.com/artifact/com.sun.jersey/jersey-server
