### ISSUE TITLE
ClassCastException if loaded by different class loaders in OSGi runtime

### ISSUE THREAD

**Issue by mmeldo** [eclipse-ee4j/jersey#5036]
## Description

Our code (Eclipse plugin) using Jersey client is running in OSGi runtime (Eclipse IDE). There are some Eclipse platforms that contain version of Jersey libraries different from that required by our plugin. Therefore our plugin puts the required version to the classpath. However, each Jersey version is then loaded by a different class loader. There are two places where this is causing problems:

- lookup of the `InjectionManagerFactory` in `org.glassfish.jersey.internal.inject.Injections`
- configuring of auto discoverable providers in  `org.glassfish.jersey.model.internal.CommonConfig`

The problem is that in those places and in this scenario, cast is done using classes from different class loaders resulting in `ClassCastException` stopping the request completely. We think these casts could be avoided and the request should be able to proceed. 

### Lookup of the InjectionManagerFactory

Note: _I have truncated the exception stack trace to show only the Jersey stuff because it is quite long with all the Eclipse stuff._

Exception:

```
java.lang.ClassCastException: class org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory cannot be cast to class org.glassfish.jersey.internal.inject.InjectionManagerFactory (org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @381dbeba; org.glassfish.jersey.internal.inject.InjectionManagerFactory is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1d49806)
	at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:74) ~[org.glassfish.jersey.core.jersey-common_3.0.4.jar:?]
	at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:44) ~[org.glassfish.jersey.core.jersey-common_3.0.4.jar:?]
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:413) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317) ~[org.glassfish.jersey.core.jersey-common_3.0.4.jar:?]
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:820) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:176) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.ClientRequest.getInjectionManager(ClientRequest.java:567) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:371) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:206) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:38) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at com.ca.endevor.service.EndevorServiceRest$DatasourceAuth.getAsJson(EndevorServiceRest.java:525) ~[com.ca.endevor.uiProject/:?]
```

 Code snippet:
https://github.com/eclipse-ee4j/jersey/blob/8f7fa9917626095a816dc2114a5c1e99a89ea11b/core-common/src/main/java/org/glassfish/jersey/internal/inject/Injections.java#L72-L93

### Configuring of AutoDiscoverable

Note: _I have truncated the exception stack trace to show only the Jersey stuff because it is quite long with all the Eclipse stuff._

Exception:

```
java.lang.ClassCastException: class org.glassfish.jersey.server.wadl.internal.WadlAutoDiscoverable cannot be cast to class org.glassfish.jersey.internal.spi.AutoDiscoverable (org.glassfish.jersey.server.wadl.internal.WadlAutoDiscoverable is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @654b2ed4; org.glassfish.jersey.internal.spi.AutoDiscoverable is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @55bc4134)
	at java.util.TreeMap.put(TreeMap.java:787) ~[?:?]
	at java.util.TreeMap.put(TreeMap.java:534) ~[?:?]
	at java.util.TreeSet.add(TreeSet.java:255) ~[?:?]
	at java.util.AbstractCollection.addAll(AbstractCollection.java:336) ~[?:?]
	at java.util.TreeSet.addAll(TreeSet.java:310) ~[?:?]
	at org.glassfish.jersey.model.internal.CommonConfig.configureAutoDiscoverableProviders(CommonConfig.java:609) ~[org.glassfish.jersey.core.jersey-common_3.0.4.jar:?]
	at org.glassfish.jersey.client.ClientConfig$State.configureAutoDiscoverableProviders(ClientConfig.java:384) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:439) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317) ~[org.glassfish.jersey.core.jersey-common_3.0.4.jar:?]
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:820) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:176) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.ClientRequest.getInjectionManager(ClientRequest.java:567) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:371) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:206) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:38) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at com.ca.endevor.service.EndevorServiceRest$DatasourceAuth.getAsJson(EndevorServiceRest.java:524) ~[com.ca.endevor.uiProject/:?]
```

Code snippet:

https://github.com/eclipse-ee4j/jersey/blob/8f7fa9917626095a816dc2114a5c1e99a89ea11b/core-common/src/main/java/org/glassfish/jersey/model/internal/CommonConfig.java#L582-L629

## Suggested solution

I have tested a solution with our code that will simply check in both places if the cast can be done. Do you think the suggested solution is OK? Or is there some other way to solve this situation? 
I can open a PR if you think the solution is OK.

**Comment by jansupol** [comment]
I do not think this is a proper solution:
- Having a single Jersey version with 2 classloaders won't work
- Having two versions of Jersey with a single classloader won't work

The issue seems to be that a single classloader sees 2 versions of Jersey, but the classloaders should be restricted to a single version of Jersey (as well as all dependencies). 

To me, when you add a check on these two places, you will get a similar ClassCastException only a little longer, there would be many places where you would get the same issue. HK2 proxy is one big example where two classloaders make issues, the injections likely will stop working. 

Perhaps you could make your OSGi headers of your app to require the EXACT version of Jersey instead of range of versions?

**Comment by mmeldo** [comment]
We are running under the Eclipse runtime, so the dependency versions are defined in the manifest. In our manifest, there already is an EXACT version (3.0.4) for Jersey:

```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: CA Endevor SCM Plug-in for Eclipse
Bundle-SymbolicName: com.ca.endevor.uiProject; singleton:=true
Bundle-Version: 18.1.8.qualifier
Bundle-Activator: com.ca.endevor.ui.UIPlugin
Bundle-Vendor: %providerName
Bundle-Localization: plugin
Bundle-ClassPath: uiEndevorProject.jar,
 lib/json-20180813.jar,
 lib/httpclient-4.5.6.jar,
 lib/httpcore-4.4.10.jar,
 lib/commons-codec-1.15.jar,
 lib/commons-configuration2-2.7.jar,
 lib/commons-io-2.11.0.jar,
 lib/commons-lang3-3.12.0.jar,
 lib/log4j-api-2.17.1.jar,
 lib/log4j-core-2.17.1.jar
Export-Package: 
 com.ca.endevor.core,
 com.ca.endevor.core.log,
 com.ca.endevor.core.utils,
 com.ca.endevor.element,
 com.ca.endevor.model,
 com.ca.endevor.service,
 com.ca.endevor.ui,
 com.ca.endevor.ui.actions,
 com.ca.endevor.ui.logview,
 com.ca.endevor.ui.views,
 com.ca.endevor.ui.wizards
Require-Bundle: org.eclipse.ui,
 org.eclipse.core.resources,
 org.eclipse.team.ui,
 org.eclipse.ui.views,
 org.eclipse.ui.ide,
 org.eclipse.team.core,
 org.eclipse.core.runtime;bundle-version="[3.2.0,4.0.0)",
 com.ibm.icu,
 org.eclipse.ui.editors;bundle-version="3.6.1",
 org.eclipse.jface.text;bundle-version="3.6.1",
 org.eclipse.search;bundle-version="3.6.0",
 org.eclipse.ui.forms;bundle-version="3.5.2",
 org.eclipse.jface,
 org.eclipse.core.expressions,
 org.eclipse.compare;bundle-version="3.5.501",
 org.eclipse.equinox.security
Import-Package: com.fasterxml.jackson.annotation;version="2.13.2",
 com.fasterxml.jackson.core;version="2.13.2",
 com.fasterxml.jackson.core.type;version="2.13.2",
 com.fasterxml.jackson.databind;version="2.13.2.2",
 com.fasterxml.jackson.dataformat.xml;version="2.13.2",
 jakarta.ws.rs;version="3.0.0",
 jakarta.ws.rs.client;version="3.0.0",
 jakarta.ws.rs.core;version="3.0.0",
 jakarta.ws.rs.ext;version="3.0.0",
 org.glassfish.jersey.client;version="[3.0.4,3.0.4]",
 org.glassfish.jersey.client.authentication;version="[3.0.4,3.0.4]",
 org.glassfish.jersey.client.filter;version="[3.0.4,3.0.4]",
 org.glassfish.jersey.inject.hk2;version="[3.0.4,3.0.4]",
 org.glassfish.jersey.internal;version="[3.0.4,3.0.4]",
 org.glassfish.jersey.media.multipart;version="[3.0.4,3.0.4]",
 org.glassfish.jersey.media.multipart.file;version="[3.0.4,3.0.4]",
 org.glassfish.jersey.message;version="[3.0.4,3.0.4]",
 org.glassfish.jersey.uri;version="[3.0.4,3.0.4]",
 org.glassfish.jersey.internal.inject;version="[3.0.4,3.0.4]"
Bundle-ActivationPolicy: lazy
Bundle-RequiredExecutionEnvironment: JavaSE-1.8
Eclipse-BundleShape: dir
```

The other version in the Eclipse platform is 2.30.1

I do not think that issue is that single classloader sees 2 versions of Jersey. As it says in the exception, the problem is that there are 2 classloaders:
 `org.eclipse.osgi.internal.loader.EquinoxClassLoader @381dbeba` vs `org.eclipse.osgi.internal.loader.EquinoxClassLoader @1d49806`
each with a different version of Jersey. 

I traced all the Jersey bundles registered by the `OsgiRegistry`, and it registers Jersey bundles for both versions. Later, when the `ServiceFinder` is looking for particular services/classes, it find them for both versions and then it throws ClassCastException when it is trying to cast from class in one classloader to the other.

In our case, we are creating only the Jersey client and I have tested my suggested changes, and did not hit any other issue. 
Of course, I do not know the code as you do, so you may know a better solution and not just adding a check to those 2 places.

**Comment by mmeldo** [comment]
First, one correction. The `ClassCastException` is not because those classes are loaded by different class loaders. It seems Eclipse runtime uses different bundle class loaders for every bundle.

But it does not change a fact that Jersey's `OsgiRegistry` class registers bundles for both versions, therefore it finds both when looking for a service provider. Last few days, I tried to persuade the Eclipse runtime (Equinox OSGi) and Jersey to register only required versions without any success.

You mentioned that it is not a proper solution to do the class cast check only on those 2 places. I have tested a solution where I put the check into the `OsgiRegistry.locateAllProviders` which constructs the list of all possible providers for particular service.
It is a simple check if the service class is assignable from the provider class. Would that be OK?

**Comment by jansupol** [comment]
Updating `OsgiRegistry` sounds good.

Ideally, `JerseyVersion#{getVersion, getBuildId}` could be used to compare incoming Jersey bundles and their version and not to register them with `OsgiRegistry` when the version differs. I have not tested that, not sure if it is feasible.

**Comment by mmeldo** [comment]
> Updating `OsgiRegistry` sounds good.
> 
> Ideally, `JerseyVersion#{getVersion, getBuildId}` could be used to compare incoming Jersey bundles and their version and not to register them with `OsgiRegistry` when the version differs. I have not tested that, not sure if it is feasible.

Thanks for the suggestion with the `JerseyVersion#{getVersion, getBuildId}`, I will check that when I have a chance.

**Comment by mmeldo** [comment]
I was trying to implement the suggestion but to me it does not seem feasible. 
Not sure, how you meant to use the `org.glassfish.jersey.internal.Version#{getVersion, getBuildId}`, but I ended up using the `org.osgi.framework.Bundle#{getVersion, getSymbolicName}`.

Anyway, In my opinion the check in the `OsgiRegistry.locateAllProviders` is better solution as it will just prevent a situation when the provider class cannot be cast to service class, which would subsequently cause an exception preventing the request to be completed. Even though it could have been completed with different services. 

Maybe I can open a PR so we can discuss the solution further.
