### ISSUE TITLE
Multipart upload not working when using GrizzlyConnectorProvider

### ISSUE THREAD

**Issue by christopher-cudennec** [eclipse-ee4j/jersey#5094]
Hi Jersey team!

I'm currently debugging an issue after upgrading Jersey from 2.35 to 2.36.

Given the following example:
```
try (var is = IOUtils.toInputStream(testFileContent, StandardCharsets.UTF_8)) {
      var bodyPart = new StreamDataBodyPart("file", is);
      FormDataMultiPart part = (FormDataMultiPart) new FormDataMultiPart().bodyPart(bodyPart);
      try (var response =
          createTarget(MultiPartFeature.class)
              .path("configurations")
              .path("documentFiles")
              .request(MediaType.TEXT_PLAIN)
              .header(HttpHeaders.AUTHORIZATION, authHeader)
              .header(ConsumerTracing.TOKEN_HEADER, TEST_CONSUMER_TOKEN)
              .post(Entity.entity(part, MediaType.MULTIPART_FORM_DATA_TYPE))) {
        String bucketUuid = response.readEntity(String.class);

        // then
        assertThat(response.getStatus()).isEqualTo(200);
        assertThat(bucketUuid).isEqualTo("1234");
      }
    }
```

My test that uses this code snippet is currently failing with the following exception / output:
```
[2022-07-07 07:34:52,646] [ERROR] [4c4c561d-6711-4b48-b57c-d54a42a8d197] o.s.c.s.j.e.WebApplicationExceptionMapper - BadRequestException thrown: 
javax.ws.rs.BadRequestException: HTTP 400 Bad Request
	at org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.readFrom(MultiPartReaderClientSide.java:164)
	at org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.readFrom(MultiPartReaderClientSide.java:69)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:233)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:212)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
	at io.opentracing.contrib.jaxrs2.serialization.TracingInterceptor.aroundReadFrom(TracingInterceptor.java:41)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:49)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1072)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:888)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:822)
	at org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:253)
	at org.glassfish.jersey.media.multipart.internal.FormDataParamValueParamProvider$ValueProvider.getEntity(FormDataParamValueParamProvider.java:84)
	at org.glassfish.jersey.media.multipart.internal.FormDataParamValueParamProvider$FormDataMultiPartProvider.apply(FormDataParamValueParamProvider.java:102)
	at org.glassfish.jersey.media.multipart.internal.FormDataParamValueParamProvider$FormDataMultiPartProvider.apply(FormDataParamValueParamProvider.java:98)
	at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.apply(ParamValueFactoryWithSource.java:50)
	at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:68)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:109)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)
	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:47)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:41)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:319)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:273)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	at io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:52)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	at io.opentracing.contrib.web.servlet.filter.TracingFilter.doFilter(TracingFilter.java:189)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:284)
	at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:722)
	at io.dropwizard.jetty.ZipExceptionHandlingGzipHandler.handle(ZipExceptionHandlingGzipHandler.java:26)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:181)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:137)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.jvnet.mimepull.MIMEParsingException: Missing start boundary
	at org.jvnet.mimepull.MIMEParser.skipPreamble(MIMEParser.java:288)
	at org.jvnet.mimepull.MIMEParser.access$300(MIMEParser.java:38)
	at org.jvnet.mimepull.MIMEParser$MIMEEventIterator.next(MIMEParser.java:124)
	at org.jvnet.mimepull.MIMEParser$MIMEEventIterator.next(MIMEParser.java:102)
	at org.jvnet.mimepull.MIMEMessage.makeProgress(MIMEMessage.java:200)
	at org.jvnet.mimepull.MIMEMessage.parseAll(MIMEMessage.java:160)
	at org.jvnet.mimepull.MIMEMessage.getAttachments(MIMEMessage.java:86)
	at org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.getMimeParts(MultiPartReaderClientSide.java:248)
	at org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.readMultiPart(MultiPartReaderClientSide.java:207)
	at org.glassfish.jersey.media.multipart.internal.MultiPartReaderServerSide.readMultiPart(MultiPartReaderServerSide.java:67)
	at org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.readFrom(MultiPartReaderClientSide.java:159)
	... 87 common frames omitted
127.0.0.1 - - [07/Juli/2022:05:34:52 +0000] "POST /api/configurations/documentFiles HTTP/1.1" 400 64 "-" "Jersey/2.36 (Async HTTP Grizzly Connector 2.36)" 181
[2022-07-07 07:34:52,736] [WARN ] [] o.g.j.message.internal.HeaderUtils - There are some request headers that have not been sent by connector [org.glassfish.jersey.grizzly.connector.GrizzlyConnector]. Probably you added those headers in WriterInterceptor or MessageBodyWriter. That feature is not supported by the connector. Please, do not modify headers in WriterInterceptor or MessageBodyWriter or use default HttpUrlConnector instead.
Unsent header changes: [MIME-Version, Content-Type]
```

I've found out the following:
* the server side code does not find a boundary that should've been sent along with the media type
* the client side code sets the boundary in the `MultiPartWriter` by overriding the `Content-Type` header
* as you can see I get a WARN message in the log: `There are some request headers that have not been sent by connector`

Can you help me finding the cause? I would expect full backwards compatibility when upgrading a minor version.

My environment:
* Java 11
* MacOS

**Edit:**
As expected the test passes if I set the boundary manually by replacing the following line in my client code:
```
.post(Entity.entity(part, MediaType.valueOf("multipart/form-data; boundary=1267412871")))) {
```

But I assume this is not want we should do.

**Edit 2:**
I found out that the issue was caused by the underlying Dropwizard framework that we use. The update from 2.1.0 to 2.1.1 changed the behaviour of providing the Jersey client. See [upgrade notes](https://www.dropwizard.io/en/latest/manual/upgrade-notes/upgrade-notes-2_1_x.html#modification-of-the-client-in-dropwizardappextension):
> Now the GrizzlyConnectorProvider is registered by default to use the Grizzly Async Http Client instead of the HttpURLConnection. Using the Grizzly client should cause no problems when migrating to Dropwizard 2.1.1.

**Comment by jansupol** [comment]
Can you try to use `HttpUrlConnector`? For instance
```
ClientConfig clientConfig = new ClientConfig();
clientConfig.connectorProvider(new HttpUrlConnectorProvider());
Client client = ClientBuilder.newClient(clientConfig);
```
It can be done automatically using `ClientBuilderListener`, too.

**Comment by christopher-cudennec** [comment]
Yes, it works. It seems to be cause by switching to `GrizzlyConnectorProvider`.

Would that be your suggested solution?
Setting the boundary manually when using Grizzly feels wrong. Although there is a warning in the logs it's not easy to find the solution.

**Comment by christopher-cudennec** [comment]
I found the following warning in the [official documentation](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/user-guide.html):

> Be aware of using other than default Connector implementation. There is an issue handling HTTP headers in WriterInterceptor or MessageBodyWriter<T>. If you need to change header fields do not use nor ApacheConnectorProvider nor GrizzlyConnectorProvider nor JettyConnectorProvider neither NettyConnectorProvider. The issue for example applies to Jersey [Multipart](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/user-guide.html#multipart) feature that also modifies HTTP headers.

Since this is known I will close the ticket for now. Still I feel that the error message is really vague and could be improved to quickly find the error.
