### ISSUE TITLE
Can't use MVC with CDI TemplateModelProcessor does not expose a no arg constructor

### ISSUE THREAD

**Issue by ieugen** [eclipse-ee4j/jersey#5168]
I am trying to use Freemarker MVC widh CDI and I get this error:

It seems that TemplateModelProcessor does not have a no-arg constructor.
It is an internal class and I wonder why it is being instantiated.

```
Caused by: java.lang.NoSuchMethodException: org.glassfish.jersey.server.mvc.internal.TemplateModelProcessor.<init>()
	at java.lang.Class.getConstructor0(Class.java:3585) ~[?:?]
	at java.lang.Class.getConstructor(Class.java:2271) ~[?:?]
	at org.glassfish.jersey.inject.cdi.se.CdiSeInjectionManager.createAndInitialize(CdiSeInjectionManager.java:111) ~[?:?]
	at org.glassfish.jersey.model.internal.ComponentBag.lambda$getFromBinders$8(ComponentBag.java:231) ~[jersey-common-2.37.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at org.glassfish.jersey.model.internal.ComponentBag.getFromBinders(ComponentBag.java:244) ~[jersey-common-2.37.jar:?]
	at org.glassfish.jersey.server.ModelProcessorConfigurator.init(ModelProcessorConfigurator.java:71) ~[jersey-server-2.37.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:343) ~[jersey-server-2.37.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:297) ~[jersey-server-2.37.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.37.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.37.jar:?]
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232) ~[jersey-common-2.37.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:296) ~[jersey-server-2.37.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:261) ~[jersey-server-2.37.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311) ~[jersey-container-servlet-core-2.37.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154) ~[jersey-container-servlet-core-2.37.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:339) ~[jersey-container-servlet-core-2.37.jar:?]
	at javax.servlet.GenericServlet.init(GenericServlet.java:180) ~[jetty-servlet-api-4.0.6.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:633) ~[jetty-servlet-10.0.12.jar:10.0.12]
	... 40 more
```

My dependencies look like this:

```
    implementation 'org.glassfish.jersey.ext:jersey-mvc-bean-validation:2.37'
    implementation 'org.glassfish.jersey.ext:jersey-mvc-freemarker:2.37'
    implementation 'org.glassfish.jersey.media:jersey-media-multipart:2.37'

    implementation 'org.glassfish.jersey.inject:jersey-cdi2-se:2.37'

```

My app looks like this + I am using @Template annotation in a resource.
```
@ApplicationPath("/hx-v1")
public class HtmxApiV1 extends ResourceConfig {
    public HtmxApiV1() {
        log.info("Creating jax-rs app");
        packages("ro.kubu.rest.v1.htmx");
        register(FreemarkerMvcFeature.class);
        register(MvcBeanValidationFeature.class);
    }
}
```

**Comment by ieugen** [comment]
I could not find any examples showing MVC + CDI combination

**Comment by jansupol** [comment]
Do you happen to have `jersey-mvc:jersey-ext-mvc` dependency, too?

**Comment by ieugen** [comment]
Not explicit. It's added as a transitive dependency. 
The exception is `java.lang.NoSuchMethodException: TemplateModelProcessor.<init>()` . 
Class exists but it does not have the method <init> - Which is the constructor.

**Comment by jansupol** [comment]
The exception looks like the class exists, but the constructor is 
```
    @Inject
    TemplateModelProcessor(final Provider<ResourceContext> resourceContextProvider,
                           final Provider<ConfiguredValidator> validatorProvider,
                           final Provider<ExtendedUriInfo> extendedUriInfoProvider) {
```
Which should work. Neither the class nor the constructor is public, though.

**Comment by ieugen** [comment]
I think it might be my fault. 
Trying to do embedded Jetty + CDI + jax-rs with Jersey. 
I might be doing things wrong. 
I spend quite a lot of time on this without success and considering switching to spring webmvc. 

Thanks for looking into this.
I think we might close this issue.

**Comment by jansupol** [comment]
It looks like the constructor needs to public. `CdiSeInjectionManager.createAndInitialize` grabs public constructor and tries to initialize it. But it would not work: at that phase `CdiSeInjectionManager` is not able to `Inject` anything to the constructor, at that phase the constructor should not be called. 

`CdiSeInjectionManager` works in two phases. First, when Weld starts, it creates all the beans, in the second phase, after Weld is started, Jersey is started, and it it also creates the instances of the CDI beans. This looks like the instance is already started to be created, but Jersey is in phase one, yet.

My guess is that you are on Jetty, and the WELD is running there, so you are in the CDI-managed environment, for which you should not use `jersey-cdi2-se`, as the `se` tries to indicate, the `jersey-cdi2-se` is for using it in the Java SE environment, where you start weld on your own. So I'd say you would be better off with the `org.glassfish.jersey.ext.cdi:jersey-cdi1x` which is mean for the EE/CDI managed environment. Do not worry about the "1x", it is more there to support CDI 1.x (as well as 2.x), which you probably have in your env.

**Comment by ieugen** [comment]
Thanks for time and explanation. 
I'll see what I can do.
