### ISSUE TITLE
JerseyTest cannot start in 3.1.0 - throws NoSuchMethodError

### ISSUE THREAD

**Issue by mdindoffer** [eclipse-ee4j/jersey#5200]
JerseyTest is broken in 3.1.0 and the test class fails to initialize. Instead an exception is thrown:
`NoSuchMethodError: 'boolean org.glassfish.jersey.internal.config.SystemPropertiesConfigurationModel.hasProperty(java.lang.String)'`.

This is a regression, 3.0.8 works just fine.

# Reproducible example

## Junit5 test

```java
import jakarta.ws.rs.core.Application;
import org.glassfish.jersey.server.ResourceConfig;
import org.glassfish.jersey.test.JerseyTest;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class DummyJerseyTest extends JerseyTest {


	@BeforeAll
	void initContainer() throws Exception {
		super.setUp();
	}

	@AfterAll
	void destroyContainer() throws Exception {
		super.tearDown();
	}

	@Override
	protected Application configure() {
		var app = new ResourceConfig();
		app.register(new Object());
		return app;
	}

	@Test
	void myTest() {
		//NOOP
	}
}
```

## Output
```
Nov 21, 2022 9:51:47 AM org.glassfish.jersey.test.jdkhttp.JdkHttpServerTestContainerFactory$JdkHttpServerTestContainer <init>
INFO: Creating JdkHttpServerTestContainer configured at the base URI http://localhost:9998/

Test ignored.

java.lang.NoSuchMethodError: 'boolean org.glassfish.jersey.internal.config.SystemPropertiesConfigurationModel.hasProperty(java.lang.String)'

	at org.glassfish.jersey.internal.config.SystemPropertiesConfigurationModel.as(SystemPropertiesConfigurationModel.java:83)
	at org.glassfish.jersey.internal.config.SystemPropertiesConfigurationModel.getProperties(SystemPropertiesConfigurationModel.java:119)
	at org.glassfish.jersey.internal.config.ExternalConfigurationProviderImpl.getProperties(ExternalConfigurationProviderImpl.java:34)
	at org.glassfish.jersey.internal.config.ExternalPropertiesConfigurationFactory.readExternalPropertiesMap(ExternalPropertiesConfigurationFactory.java:65)
	at org.glassfish.jersey.internal.config.ExternalPropertiesConfigurationFactory.configure(ExternalPropertiesConfigurationFactory.java:95)
	at org.glassfish.jersey.internal.config.ExternalPropertiesConfigurationFactory.configure(ExternalPropertiesConfigurationFactory.java:76)
	at org.glassfish.jersey.server.ResourceConfig.lock(ResourceConfig.java:743)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:328)
	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:310)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:309)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:274)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:249)
	at org.glassfish.jersey.jdkhttp.JdkHttpHandlerContainer.<init>(JdkHttpHandlerContainer.java:72)
	at org.glassfish.jersey.jdkhttp.JdkHttpServerFactory.createHttpServer(JdkHttpServerFactory.java:86)
	at org.glassfish.jersey.test.jdkhttp.JdkHttpServerTestContainerFactory$JdkHttpServerTestContainer.<init>(JdkHttpServerTestContainerFactory.java:58)
	at org.glassfish.jersey.test.jdkhttp.JdkHttpServerTestContainerFactory$JdkHttpServerTestContainer.<init>(JdkHttpServerTestContainerFactory.java:43)
	at org.glassfish.jersey.test.jdkhttp.JdkHttpServerTestContainerFactory.create(JdkHttpServerTestContainerFactory.java:101)
	at org.glassfish.jersey.test.JerseyTest.createTestContainer(JerseyTest.java:262)
	at org.glassfish.jersey.test.JerseyTest.setUp(JerseyTest.java:621)
	at com.example.rest.DummyJerseyTest.initContainer(DummyJerseyTest.java:17)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:128)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeAllMethod(TimeoutExtension.java:70)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllMethods$13(ClassBasedTestDescriptor.java:411)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllMethods(ClassBasedTestDescriptor.java:409)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:215)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:84)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)


Process finished with exit code 255
```

**Comment by jbescos** [comment]
I am trying it in latest 3.1 branch and it works fine. But you have to remove:
```
	@BeforeAll
	void initContainer() throws Exception {
		super.setUp();
	}

	@AfterAll
	void destroyContainer() throws Exception {
		super.tearDown();
	}
```

That is automatically done by JerseyTest. Otherwise you will get `java.net.BindException: Address already in use`

**Comment by mdindoffer** [comment]
> `SystemPropertiesConfigurationModel.hasProperty(java.lang.String)` is inherited from new Jakarta REST 3.1 API `Configuration#hasProperty`. Do you use the proper 3.1.0 API?

Yes. 
![image](https://user-images.githubusercontent.com/12681399/203034491-b89c5e64-7a4b-4240-a694-d1adc988a670.png)

> I am trying it in latest 3.1 branch and it works fine. But you have to remove:

Nope. The full example is:

```java
//Let's avoid the expensive recreation of the jax-rs container for each test method by setting up class-level container instance
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class MyTest extends JerseyTest {

	@BeforeAll
	void initContainer() throws Exception {
		super.setUp();
	}

	@AfterAll
	void destroyContainer() throws Exception {
		super.tearDown();
	}

	@BeforeEach
	public void initDb() {
		someinit();
	}

	@Override
	public void setUp() throws Exception {
		//NOOP to avoid recreating container
	}

	@Override
	public void tearDown() throws Exception {
		//NOOP to avoid recreating container
	}
...
```
I just omitted the overrides for brevity. And even if I remove all that I still get the `NoSuchMethodError`.

**Comment by jbescos** [comment]
@mdindoffer you can try my example.

```
$ git clone https://github.com/jbescos/Questions.git
$ cd jersey3.1
$ mvn clean install
...
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.283 s - in com.github.jbescos.jersey3.DummyJerseyTest
...

```

```
[INFO] com.example:jersey3:jar:1.0
[INFO] +- org.glassfish.jersey.containers:jersey-container-servlet-core:jar:3.1.0:compile
[INFO] |  +- jakarta.inject:jakarta.inject-api:jar:2.0.1:compile
[INFO] |  +- org.glassfish.jersey.core:jersey-common:jar:3.1.0:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:2.1.1:compile
[INFO] |  |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.3:compile
[INFO] |  +- org.glassfish.jersey.core:jersey-server:jar:3.1.0:compile
[INFO] |  |  \- jakarta.validation:jakarta.validation-api:jar:3.0.2:compile
[INFO] |  \- jakarta.ws.rs:jakarta.ws.rs-api:jar:3.1.0:compile
[INFO] +- org.glassfish.jersey.inject:jersey-hk2:jar:3.1.0:compile
[INFO] |  +- org.glassfish.hk2:hk2-locator:jar:3.0.3:compile
[INFO] |  |  +- org.glassfish.hk2.external:aopalliance-repackaged:jar:3.0.3:compile
[INFO] |  |  +- org.glassfish.hk2:hk2-api:jar:3.0.3:compile
[INFO] |  |  \- org.glassfish.hk2:hk2-utils:jar:3.0.3:compile
[INFO] |  \- org.javassist:javassist:jar:3.28.0-GA:compile
[INFO] +- org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-jdk-http:jar:3.1.0:test
[INFO] |  +- org.glassfish.jersey.test-framework:jersey-test-framework-core:jar:3.1.0:test
[INFO] |  |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:4.0.0:test
[INFO] |  |  |  \- jakarta.activation:jakarta.activation-api:jar:2.1.0:test
[INFO] |  |  +- jakarta.servlet:jakarta.servlet-api:jar:6.0.0:test
[INFO] |  |  \- org.glassfish.jersey.media:jersey-media-jaxb:jar:3.1.0:test
[INFO] |  +- org.glassfish.jersey.containers:jersey-container-jdk-http:jar:3.1.0:test
[INFO] |  +- org.glassfish.jersey.core:jersey-client:jar:3.1.0:compile
[INFO] |  \- junit:junit:jar:4.13.1:test
[INFO] |     \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] \- org.junit.jupiter:junit-jupiter:jar:5.9.1:test
[INFO]    +- org.junit.jupiter:junit-jupiter-api:jar:5.9.1:test
[INFO]    |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO]    |  +- org.junit.platform:junit-platform-commons:jar:1.9.1:test
[INFO]    |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO]    +- org.junit.jupiter:junit-jupiter-params:jar:5.9.1:test
[INFO]    \- org.junit.jupiter:junit-jupiter-engine:jar:5.9.1:test
[INFO]       \- org.junit.platform:junit-platform-engine:jar:1.9.1:test
```

Could you check the classpath/modulepath of the running test?. Just add a `Thread.sleep(9999999);` right after `void initContainer() throws Exception {` and run `$ ps -ef | grep java`.

**Comment by mdindoffer** [comment]
Sorry this took so long. I've tracked this down to `jakarta.platform:jakarta.jakartaee-api:9.1.0` on our classpath.
This `jakartaee-api` artifact also includes the `jakarta.ws.rs.core.Configuration` class, just as the `jakarta.ws.rs:jakarta.ws.rs-api:3.1.0` does. But, the `Configuration` class in jakartaee-api 9.1.0 differs from the one in rs-api 3.1.0.

Obviously I could update `jakartaee-api` to 10.0.0, which fixes the test at least. But I wonder if this is really the intended way to manage jakarta dependencies. It seems horribly wrong to have the same class on classpath supplied by two different jakarta artifacts. It is hard to keep everything in sync this way.

What is the recommended way to pull in jakarta APIs ? Why are the classes duplicated in different artifacts? Should I try to 
1. Exclude the individual api artifacts like `rs-api` from jersey and other 3rd party libs? or
2. Exclude the `jakartaee-api` artifacts from my project and 3rd party libs?
3. Keep both in, but try to keep this fragile mess in sync all the time?

**Comment by jansupol** [comment]
@mdindoffer Glad to hear you were able to solve the issue. Mixing the versions between Jakarta EE 9 and Jakarta EE 10 can cause these types of issues.

The existence of `jakarta.platform:jakarta.jakartaee-api` is a result of the Jakarta EE platform project, which covers all the Jakarta EE specification. The API can be used so that each individual dependency is not required to be specified separately with its own version. The drawback is that there are many dependencies not used by project but forced on the classpath/module path.

To answer the questions:

1. Jersey does not include the APIs (except for bundles which likely are not used in your project). Jersey has some mandatory dependencies, such as Jakarta REST API, but those are required to be added by a customer. Jersey, as well as all the Jakarta EE artifacts, define OSGi headers in each of the artifacts which define the versions of dependencies Jersey relies on. These OSGi headers are defined in MANIFEST.MF of each maven artifact (jar) and the dependency versions are enforced by some application servers that are using the OSGi runtime, such as Glassfish, or Payara. In your pure maven (or ANT) test environment the OSGi framework (such as Felix) most likely is not used (setting up the OSGi environment is difficult) and the dependencies can be freely mixed, causing the issues. The proper dependency versions can also be seen in Jersey pom.xml files.

2. You can choose which dependency you would use, whether the all-API-bundle `jakartaee-api` or the individual API. When the JPMS would be used by your project, the `jakartaee-api` might have issues with declaring the `module-info`, though.

3. It is possible to use many APIs each providing the same classes. The one to be the first on the classpath/module path would be used by the classloader.

With JakartaEE dependencies, it is important to know which Jakarta EE version your project wants to support. When upgrading the version (such as in your case from Jakarta EE 9 to Jakarta EE 10 with Jersey 3.0.x to 3.1.x), all the dependencies should be upgraded accordingly, JAX-B, JSON-B, CDI, Servlet, you name it. So upgrading the Jakarta EE version is rather a larger task. But it is performed only with a new Jakarta EE release, i.e. next time no sooner than in 2024.

**Comment by mdindoffer** [comment]
Thanks for the explanation, I'm closing this as it's a simple mixup of JEE10 and 9.1 dependencies.
In other words, everything should be updated all at once (Jetty, Jersey, and any other library that depends on JEE specs), mixing is not allowed.

What is interesting though is that Jersey 3.1.x was out for quite some time since November 2022, while Jetty 12 (the first version with support for JEE10) came out just two weeks ago. I wonder how did other folks use Jersey 3.1, when the rest of the ecosystem was way behind playing catch-up.
