### ISSUE TITLE
Jersey client running in a web start application makes unexpected requests

### ISSUE THREAD

**Issue by ansanes** [eclipse-ee4j/jersey#5235]
Hello. I'm using these jersey libraries:
```
        <dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-client</artifactId>
            <version>2.34</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-json-jackson</artifactId>
            <version>2.34</version>
        </dependency>     
        <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-sse</artifactId>
            <version>2.34</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.inject</groupId>
            <artifactId>jersey-hk2</artifactId>
            <version>2.34</version>
        </dependency>        
```
My java application is packaged into a uber-jar (MyApplication-1.0.jar in the jnlp file) that includes my code and all the dependencies.
It is a headless java application that makes API requests using jax-rs and jersey libraries.
It runs on multiple devices using java web start ([https://github.com/AdoptOpenJDK /IcedTea-Web](https://github.com/AdoptOpenJDK/IcedTea-Web]) 

I have noticed that from time to time some devices start making requests for the MyApplication-1.0.jar file . I can see that on my webserver access log. 

I've run this test where I remove the jnlp and the jar file from the webserver and found that the devices where the application was already running and were requesting the .jar file over and over started producing this exception:

`org.glassfish.jersey.internal.inject.InjectionManagerFactory: : java.io.FileNotFoundException: https://dev.myapplication.com/MyApplication-1.0.jar  `

every time a new Rest API request to the server was being done.

What can be happening here? How is the jersey client messed up when running inside java web start for it to start producing all this requests?

this is the full stacktrace
`
org.glassfish.jersey.internal.ServiceConfigurationError: org.glassfish.jersey.internal.inject.InjectionManagerFactory: : java.io.FileNotFoundException: https://dev.myapplication.com/MyApplication-1.0.jar  at org.glassfish.jersey.internal.ServiceFinder.fail(ServiceFinder.java:410) at org.glassfish.jersey.internal.ServiceFinder.parse(ServiceFinder.java:489) at org.glassfish.jersey.internal.ServiceFinder.access$400(ServiceFinder.java:132) at org.glassfish.jersey.internal.ServiceFinder$LazyObjectIterator.hasNext(ServiceFinder.java:686) at org.glassfish.jersey.internal.inject.Injections.lookupService(Injections.java:88) at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:73) at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:44) at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:413) at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317) at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:819) at org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:176) at org.glassfish.jersey.client.ClientRequest.getInjectionManager(ClientRequest.java:567) at org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:371) at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:206) at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:38) at com.mycompany.myapp.restclient.MyAppJerseyClient.updateUserData(MyAppJerseyClient.java:164)    <------ my application api request

`

**Comment by jansupol** [comment]
This is happening when a request creates a client and for the client, the InjectionManager is instantiated. There can be multiple implementations of the Injection managers and the ServiceFinder looks them up. I'd recommend caching the Client/WebTarget for requests made on the same endpoints so that the InjectionManager is reused, and it does not need to be looked up every time the request is sent.

Not sure if that helps your issue, but the issue happens from to time, as you describe, it can. If it is more of a regular issue rather than intermittent, we would like to see a reproducer. The ServiceFinder implements some techniques to access various archive types, maybe JNLP is somewhat special. I admit that we do not test JNLP behavior.

**Comment by ansanes** [comment]
> This is happening when a request creates a client and for the client, the InjectionManager is instantiated. There can be multiple implementations of the Injection managers and the ServiceFinder looks them up. I'd recommend caching the Client/WebTarget for requests made on the same endpoints so that the InjectionManager is reused, and it does not need to be looked up every time the request is sent.
> 
> Not sure if that helps your issue, but the issue happens from to time, as you describe, it can. If it is more of a regular issue rather than intermittent, we would like to see a reproducer. The ServiceFinder implements some techniques to access various archive types, maybe JNLP is somewhat special. I admit that we do not test JNLP behavior.

Initially, I was reusing the same webtarget for my requests but after finding this issue I changed to creating a new webtarget every time to see if it was helping with the issue but didn't.

I was not able to reproduce the issue myself. It happened on an environment with around 500 clients running and this was happening on around 6 or 7 devices at a time after running the app for multiple days (some devices started having this behaviour the first day, others after 2 or 3).

We had to stop using java web start as the traffic related hosting costs increased a lot because of this.
