### ISSUE TITLE
Can we make rest call to jetty 10 server using jersey 1.19? 

### ISSUE THREAD

**Issue by Naziburjec** [eclipse-ee4j/jersey#5258]
We used jetty 9.4.14.v20181114 and jersey 1.19, which is working fine. Now, we are upgrading to jetty 10 but we are getting below ssl exception.

```
  Caused by: com.sun.jersey.api.client.ClientHandlerException: javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
22:32:31      	at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:155)
22:32:31      	at com.sun.jersey.api.client.Client.handle(Client.java:652)
22:32:31      	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
22:32:31      	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
22:32:31      	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:509)
```

Is there any possible way we can make call to jetty 10 server using jersey 1.19?

**Comment by jansupol** [comment]
As you can see in the Jetty [download page](https://www.eclipse.org/jetty/download.php), the minimum Java version for Jetty 10 is Java 11. But Jersey 1.x (1.19) does not support Java 11.
