### ISSUE TITLE
Spring6-jersey CDI / integration failing due to HK2 injection

### ISSUE THREAD

**Issue by jaksnair** [eclipse-ee4j/jersey#5264]
Spring4-jersey integration was working fine until a java 17 migration was attempted. 
As part of the migration, dependencies modified to spring6 (6.0.4)-jersey(3.1.1).

However the request scope is failing with the below exception.
`Getting the exception org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available in __HK2_Generated_0 for injection at SystemInjecteeImpl(requireType=XYZ, parent=ABC, qualifiers={},position=0,optional=false,self=false,unqualified=null,5088)...`

Question around the class, in version 3.1.1,  
`public class SpringComponentProvider implements ComponentProvider `
initialize()  is just checking jdk version where as the older version (eg:2.36) was trying to bridge with HK2 injection and was able to inject the  beans created in the spring container. 

Especially why is jersey-cdi relying on hk2 and not looking for spring cdi offered ?

```
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:702)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getInstance(AbstractHk2InjectionManager.java:160) 
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getInstance(ImmediateHk2InjectionManager.java:30) 
	at org.glassfish.jersey.internal.inject.Injections.getOrCreate(Injections.java:105) 
	at org.glassfish.jersey.server.model.MethodHandler$ClassBasedMethodHandler.getInstance(MethodHandler.java:260)
	at org.glassfish.jersey.server.internal.routing.PushMethodHandlerRouter.apply(PushMethodHandlerRouter.java:51)
```

The dependencies in place : 

- org.springframework:spring-web -> 6.04
- org.springframework:spring-context -> 6.04
- org.glassfish.jersey.ext:jersey-spring6 -> 3.1.1
- org.glassfish.jersey.containers:jersey-container-servlet -> 3.1.1
- org.glassfish.jersey.containers.glassfish:jersey-gf-cdi ->3.1.1
- org.glassfish.jersey.ext.cdi:jersey-cdi1x -> 3.1.1
- jakarta.servlet:jakarta.servlet-api -> 2.0.1
- jakarta.ws.rs:jakarta.ws.rs-api -> 3.1.0

Any explicit configurations to be made for this to work ? 
Any inputs or help much appreciated.

**Comment by jaksnair** [comment]
https://github.com/eclipse-ee4j/jersey/issues/5093#issuecomment-1437621683

**Comment by jaksnair** [comment]
Tagging @senivam @wilkinsona  , for quick reach / help.

**Comment by wilkinsona** [comment]
Spring Framework 6.0 requires Jakarta EE 9 as a minimum. EE 10 is also supported. A number of your spec jars appear to be from EE 8 or earlier. Spring Framework 5.3.x supports Java 17 so an upgrade to 6.0 isn't necessary to use Java 17.

**Comment by jaksnair** [comment]
@wilkinsona  Thanks for looking into it. 

What I tried to bring into your attention is that the jersey-spring6-3.1.1 package does have the required SpringComponentProvider implementation and its failing the consumer's end. 

Just noticed that the repo has the code : https://github.com/eclipse-ee4j/jersey/blob/3.1/ext/spring6/src/main/java17/org/glassfish/jersey/server/spring/SpringComponentProvider.java

however, the decompiled version of jersey-spring6-3.1.1.jar doesn't have the required initialize() and binding() handling to inject the spring provided beans to HK2 injection implementation. See this screenshot of the decompiled class.

<img width="442" alt="Screen Shot 2023-02-22 at 12 07 14 PM" src="https://user-images.githubusercontent.com/38532997/220747917-f9b4c115-84eb-41d4-9428-a6789ec60806.png">

**Comment by wilkinsona** [comment]
I suspect you're looking at the wrong class. `jersey-spring6` is a multi-release jar file. When running on Java 17, the class beneath `META-INF/versions/17` is used.

**Comment by jaksnair** [comment]
Thanks @wilkinsona . Got to know how multi release versioned classes are kept.

**Comment by jansupol** [comment]
I am not sure that I fully understand the issue. There are three injection frameworks mixed together, HK2, CDI, and Spring, correct? And the problem is that with Jersey 2.x it used to work fine, whereas, with 3.1.1, it does not work. Correct?

I suspect the dependencies could have been wrong. I am not sure what is the `org.glassfish.jersey.containers.glassfish:jersey-gf-cdi ->3.1.1`, it is not a Jersey module. Anyway, are you using the correct Weld 5?

**Comment by KowalczykBartek** [comment]
If you are using embedded tomcat and you are producing shadow jar using gradle, you will have to 
```
'Multi-Release': 'true'
```
https://stackoverflow.com/questions/52953483/logmanager-getlogger-is-unable-to-determine-class-name-on-java-11

I guess similar issue can appear to other packaging tools

**Comment by emil6strutui** [comment]
Any updates/fixes regarding this issue?

**Comment by jansupol** [comment]
@emil6strutui We do not hit this issue. Can you provide us reproducer of your issue?

**Comment by emil6strutui** [comment]
I am using Spring version 6.0.9 and jersey 3.1.1

Registering my controller inside my Application Config and then my example controller looks like the following.
``` java
@ApplicationPath("/api")
public class ApplicationConfig extends ResourceConfig {

    public ApplicationConfig() {

        //Spring DI
        register(SpringComponentProvider.class);
        register(ExampleController.class);
    }
}
```

```java
@Path("/v1/example")
@RequiredArgsConstructor(onConstructor = @__(@Autowired))
public class ExampleController {

    private final ExampleService exampleService;
    
    @GET
    @Path("/example-get")
    public void exampleEndpoint(@Suspended final AsyncResponse asyncResponse) {

        final var executorService = getExecutorService();
        computeAsync(() -> exampleService.getExample(), executorService)
                .thenApplyAsync(json -> asyncResponse.resume(status(200).entity(json).build()), executorService)
                .exceptionally(error -> asyncResponse.resume(handleException((CompletionException) error)));
    }
    
}
```
When I try to access the get endpoint the I get an error saying that no suitable constructor is found.
I want to mention that I have custom UndertowServer setup.

```java
private static ListenerInfo createContextLoaderListener(WebApplicationContext context) {
        InstanceFactory<ContextLoaderListener> factory = new ImmediateInstanceFactory<>(new ContextLoaderListener(context));
        return new ListenerInfo(ContextLoaderListener.class, factory);
    }

    private HttpHandler bootstrap() throws ServletException {
        final DeploymentInfo servletBuilder = deployment()
                .setClassLoader(Server.class.getClassLoader())
                .setContextPath("/")
                .addListeners(createContextLoaderListener(getSpringApplicationContext()))
                .setResourceManager(new ClassPathResourceManager(Server.class.getClassLoader(), "webapp/resources"))
                .addWelcomePage("index.html")
                .setDeploymentName(deploymentName)

                .addServlets(
                        servlet("jerseyServlet", ServletContainer.class)
                                .addInitParam(APPLICATION_NAME, com.api.config.ApplicationConfig.class.getName())
                                .addMapping("/api/*")
                                .setLoadOnStartup(1)
                                .setAsyncSupported(true)
                );

        final DeploymentManager manager = defaultContainer().addDeployment(servletBuilder);
        manager.deploy();

        //Servlet handler
        final HttpHandler servletHandler = manager.start();


        return Handlers.path()
                .addPrefixPath("/", servletHandler);
    }
```

I want to mention that the same setup worked before upgrading to jersey 3.1.1
