### ISSUE TITLE
Jersey 3.1.1 server throws java.lang.NoClassDefFoundError: javax/ws/rs/core/Configuration

### ISSUE THREAD

**Issue by rsandidfc** [eclipse-ee4j/jersey#5353]
Similar to #5135 but the solution to that case doesn't apply. The Jersey Server is running on Tomcat 10.1.8. It fails to load my Application class. I've been banging my head against this for three days trying to figure out where on earth its looking for the old javax.ws.rs.core but can't find it. Any help greatly appreciated!

```
[2023-06-22 11:21:55.281][main][INFO][][][o.g.jersey.server.ApplicationHandler][ssorest-aco] - [Initiating Jersey application, version Jersey: 3.1.1 2023-01-30 15:17:48...]
[2023-06-22 11:21:55.464][main][DEBUG][][][jakarta.xml.bind][ssorest-aco] - [Resolved classes from context path: [class com.sun.research.ws.wadl.ObjectFactory]]
[2023-06-22 11:21:55.466][main][DEBUG][][][jakarta.xml.bind][ssorest-aco] - [Checking system property jakarta.xml.bind.JAXBContextFactory]
[2023-06-22 11:21:55.468][main][DEBUG][][][jakarta.xml.bind][ssorest-aco] - [  not found]
[2023-06-22 11:21:55.469][main][DEBUG][][][jakarta.xml.bind][ssorest-aco] - [Checking system property jakarta.xml.bind.context.factory]
[2023-06-22 11:21:55.470][main][DEBUG][][][jakarta.xml.bind][ssorest-aco] - [  not found]
[2023-06-22 11:21:55.470][main][DEBUG][][][jakarta.xml.bind][ssorest-aco] - [Checking system property jakarta.xml.bind.JAXBContext]
[2023-06-22 11:21:55.471][main][DEBUG][][][jakarta.xml.bind][ssorest-aco] - [  not found]
[2023-06-22 11:21:55.474][main][DEBUG][][][jakarta.xml.bind][ssorest-aco] - [ServiceProvider loading Facility used; returning object [org.glassfish.jaxb.runtime.v2.JAXBContextFactory]]
[2023-06-22 11:21:55.482][main][DEBUG][][][o.g.jaxb.runtime.v2.ContextFactory][ssorest-aco] - [Property org.glassfish.jaxb.XmlAccessorFactoryis not active.  Using JAXB's implementation]
[2023-06-22 11:21:55.795][main][INFO][][][org.glassfish.jersey.internal.Errors][ssorest-aco] - [The following hints have been detected: HINT: Cannot create new registration for component type class org.glassfish.jersey.media.multipart.Multi
PartFeature: Existing previous registration found for the type.
]
[2023-06-22 11:21:55.798][main][ERROR][][][o.a.c.c.C.[.[localhost].[/ssorest]][ssorest-aco] - [Servlet.init() for servlet [com.idfconnect.ssorest.gateway.SSORestApp] threw exception]
java.lang.NoClassDefFoundError: javax/ws/rs/core/Configuration
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3167)
        at java.base/java.lang.Class.getDeclaredMethods(Class.java:2310)
        at org.glassfish.jersey.server.model.IntrospectionModeller$2.run(IntrospectionModeller.java:237)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.glassfish.jersey.server.model.IntrospectionModeller.getAllDeclaredMethods(IntrospectionModeller.java:231)
        at org.glassfish.jersey.server.model.IntrospectionModeller.checkForNonPublicMethodIssues(IntrospectionModeller.java:151)
        at org.glassfish.jersey.server.model.IntrospectionModeller.doCreateResourceBuilder(IntrospectionModeller.java:98)
        at org.glassfish.jersey.server.model.IntrospectionModeller.access$000(IntrospectionModeller.java:59)
        at org.glassfish.jersey.server.model.IntrospectionModeller$1.call(IntrospectionModeller.java:91)
        at org.glassfish.jersey.server.model.IntrospectionModeller$1.call(IntrospectionModeller.java:88)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
        at org.glassfish.jersey.server.model.IntrospectionModeller.createResourceBuilder(IntrospectionModeller.java:88)
        at org.glassfish.jersey.server.model.Resource.from(Resource.java:781)
        at org.glassfish.jersey.server.ResourceBagConfigurator.init(ResourceBagConfigurator.java:66)
        at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:348)
        at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:310)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
        at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:309)
        at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:274)
        at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
        at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
        at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:338)
        at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
        at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:944)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:808)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4633)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4926)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:683)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:658)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:713)
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:641)
        at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1927)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
        at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:534)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:424)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1656)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:898)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:846)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:871)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:241)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:428)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:913)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:795)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)
Caused by: java.lang.ClassNotFoundException: javax.ws.rs.core.Configuration
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1437)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1245)
        ... 72 common frames omitted
```

My maven dependencies already include Jersey Client 3.1.1, and there are no javax dependencies in the hierarchy:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------< com.idfconnect.ssorest.gateway:gateway-core >-------------
[INFO] Building SSO/Rest Gateway Core 3.2.0-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ gateway-core ---
[INFO] com.idfconnect.ssorest.gateway:gateway-core:war:3.2.0-SNAPSHOT
[INFO] +- org.glassfish.jersey.core:jersey-server:jar:3.1.1:compile
[INFO] |  +- org.glassfish.jersey.core:jersey-common:jar:3.1.1:compile
[INFO] |  |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.3:compile
[INFO] |  +- jakarta.ws.rs:jakarta.ws.rs-api:jar:3.1.0:compile
[INFO] |  +- jakarta.annotation:jakarta.annotation-api:jar:2.1.1:compile
[INFO] |  +- jakarta.inject:jakarta.inject-api:jar:2.0.1:compile
[INFO] |  \- jakarta.validation:jakarta.validation-api:jar:3.0.2:compile
[INFO] +- org.glassfish.jersey.containers:jersey-container-servlet:jar:3.1.1:compile
[INFO] |  \- org.glassfish.jersey.containers:jersey-container-servlet-core:jar:3.1.1:compile
[INFO] +- org.slf4j:jcl-over-slf4j:jar:2.0.3:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:2.0.3:compile
[INFO] +- org.slf4j:jul-to-slf4j:jar:2.0.3:compile
[INFO] +- org.slf4j:log4j-over-slf4j:jar:2.0.3:compile
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.5.14:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.16:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.11:compile
[INFO] +- org.glassfish.jersey.connectors:jersey-apache-connector:jar:3.1.1:compile
[INFO] +- jakarta.servlet:jakarta.servlet-api:jar:5.0.0:provided
[INFO] +- com.idfconnect.ssorest:common-tools:jar:3.2.0-SNAPSHOT:compile
[INFO] |  +- org.apache.commons:commons-text:jar:1.9:compile
[INFO] |  +- com.idfconnect.ssorest:common-collections:jar:3.2.0-SNAPSHOT:compile
[INFO] |  |  \- com.idfconnect.ssorest:ssorest-common:jar:3.2.0-SNAPSHOT:compile
[INFO] |  +- com.google.guava:guava:jar:31.1-jre:compile
[INFO] |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  |  +- org.checkerframework:checker-qual:jar:3.12.0:compile
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.11.0:compile
[INFO] |  |  \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] |  +- org.reflections:reflections:jar:0.10.2:compile
[INFO] |  +- commons-cli:commons-cli:jar:1.4:compile
[INFO] |  +- com.jcabi:jcabi-manifests:jar:1.1:compile
[INFO] |  |  \- com.jcabi:jcabi-log:jar:0.14:compile
[INFO] |  +- com.idfconnect.ssorest:common-annotations:jar:3.2.0-SNAPSHOT:compile
[INFO] |  +- com.idfconnect.ssorest:common-utils:jar:3.2.0-SNAPSHOT:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.15.0:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.15.0:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.15.0:compile
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:3.0.1:compile
[INFO] |  \- org.glassfish.jaxb:jaxb-runtime:jar:3.0.0:runtime
[INFO] |     \- org.glassfish.jaxb:jaxb-core:jar:3.0.0:runtime
[INFO] |        +- org.glassfish.jaxb:txw2:jar:3.0.0:runtime
[INFO] |        \- com.sun.istack:istack-commons-runtime:jar:4.0.0:runtime
[INFO] +- com.idfconnect.ssorest:common-tools:jar:tests:3.2.0-SNAPSHOT:test
[INFO] +- junit:junit:jar:4.13.2:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.glassfish.jersey.core:jersey-client:jar:3.1.1:compile
[INFO] +- com.idfconnect.ssorest:messages-json:jar:3.2.0-SNAPSHOT:compile
[INFO] |  +- com.idfconnect.ssorest:common-config:jar:3.2.0-SNAPSHOT:compile
[INFO] |  |  \- com.idfconnect.ssorest:common-crypto:jar:3.2.0-SNAPSHOT:compile
[INFO] |  +- com.idfconnect.ssorest.httpagent.framework:framework-lifecycle:jar:3.2.0-SNAPSHOT:compile
[INFO] |  |  \- com.idfconnect.ssorest:logging-framework:jar:3.2.0-SNAPSHOT:compile
[INFO] |  |     \- com.idfconnect.ssorest:logging-framework-internal:jar:3.2.0-SNAPSHOT:compile
[INFO] |  |        \- ch.qos.logback:logback-core:jar:1.4.6:compile
[INFO] |  \- com.google.code.gson:gson:jar:2.10.1:compile
[INFO] +- com.idfconnect.ssorest:common-oauth:jar:3.2.0-SNAPSHOT:compile
[INFO] +- org.apache.commons:commons-pool2:jar:2.11.1:compile
[INFO] +- org.testng:testng:jar:6.9.8:test
[INFO] |  +- com.beust:jcommander:jar:1.48:test
[INFO] |  +- org.apache.ant:ant:jar:1.7.0:test
[INFO] |  |  \- org.apache.ant:ant-launcher:jar:1.7.0:test
[INFO] |  +- com.google.inject:guice:jar:no_aop:4.0:test
[INFO] |  |  +- javax.inject:javax.inject:jar:1:test
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:test
[INFO] |  \- org.beanshell:bsh:jar:2.0b4:test
[INFO] +- org.glassfish.jersey.media:jersey-media-multipart:jar:3.1.1:compile
[INFO] |  \- org.jvnet.mimepull:mimepull:jar:1.9.15:compile
[INFO] +- com.idfconnect.ssorest.plugin:plugin-common:jar:3.2.0-SNAPSHOT:compile
[INFO] |  +- commons-io:commons-io:jar:1.4:compile
[INFO] |  +- org.glassfish.jersey.inject:jersey-hk2:jar:3.1.1:compile
[INFO] |  |  \- org.glassfish.hk2:hk2-locator:jar:3.0.3:compile
[INFO] |  |     +- org.glassfish.hk2.external:aopalliance-repackaged:jar:3.0.3:compile
[INFO] |  |     +- org.glassfish.hk2:hk2-api:jar:3.0.3:compile
[INFO] |  |     \- org.glassfish.hk2:hk2-utils:jar:3.0.3:compile
[INFO] |  \- com.github.rholder:guava-retrying:jar:2.0.0:compile
[INFO] +- io.swagger.core.v3:swagger-jaxrs2-jakarta:jar:2.2.10:compile
[INFO] |  +- io.github.classgraph:classgraph:jar:4.8.154:compile
[INFO] |  +- org.javassist:javassist:jar:3.29.2-GA:compile
[INFO] |  +- io.swagger.core.v3:swagger-models-jakarta:jar:2.2.10:compile
[INFO] |  +- io.swagger.core.v3:swagger-annotations-jakarta:jar:2.2.10:compile
[INFO] |  +- io.swagger.core.v3:swagger-integration-jakarta:jar:2.2.10:compile
[INFO] |  |  \- io.swagger.core.v3:swagger-core-jakarta:jar:2.2.10:compile
[INFO] |  |     +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.14.2:compile
[INFO] |  |     \- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.14.2:compile
[INFO] |  +- org.yaml:snakeyaml:jar:2.0:compile
[INFO] |  \- com.fasterxml.jackson.jakarta.rs:jackson-jakarta-rs-json-provider:jar:2.14.2:compile
[INFO] |     +- com.fasterxml.jackson.jakarta.rs:jackson-jakarta-rs-base:jar:2.14.2:compile
[INFO] |     \- com.fasterxml.jackson.module:jackson-module-jakarta-xmlbind-annotations:jar:2.14.2:compile
[INFO] +- io.swagger.core.v3:swagger-jaxrs2-servlet-initializer-v2-jakarta:jar:2.2.10:compile
[INFO] +- org.projectlombok:lombok:jar:1.18.24:provided
[INFO] +- org.glassfish.web:jakarta.servlet.jsp.jstl:jar:3.0.1:compile
[INFO] +- jakarta.platform:jakarta.jakartaee-api:jar:10.0.0:provided
[INFO] |  +- jakarta.platform:jakarta.jakartaee-web-api:jar:10.0.0:provided
[INFO] |  |  +- jakarta.servlet.jsp:jakarta.servlet.jsp-api:jar:3.1.0:provided
[INFO] |  |  +- jakarta.el:jakarta.el-api:jar:5.0.1:compile
[INFO] |  |  +- jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:jar:3.0.0:provided
[INFO] |  |  +- jakarta.faces:jakarta.faces-api:jar:4.0.1:provided
[INFO] |  |  +- jakarta.websocket:jakarta.websocket-api:jar:2.1.0:provided
[INFO] |  |  +- jakarta.websocket:jakarta.websocket-client-api:jar:2.1.0:provided
[INFO] |  |  +- jakarta.json:jakarta.json-api:jar:2.1.0:provided
[INFO] |  |  +- jakarta.json.bind:jakarta.json.bind-api:jar:3.0.0:provided
[INFO] |  |  +- jakarta.ejb:jakarta.ejb-api:jar:4.0.1:provided
[INFO] |  |  +- jakarta.transaction:jakarta.transaction-api:jar:2.0.1:provided
[INFO] |  |  +- jakarta.persistence:jakarta.persistence-api:jar:3.1.0:provided
[INFO] |  |  +- jakarta.interceptor:jakarta.interceptor-api:jar:2.1.0:compile
[INFO] |  |  +- jakarta.enterprise:jakarta.enterprise.lang-model:jar:4.0.1:provided
[INFO] |  |  +- jakarta.authentication:jakarta.authentication-api:jar:3.0.0:provided
[INFO] |  |  \- jakarta.security.enterprise:jakarta.security.enterprise-api:jar:3.0.0:provided
[INFO] |  +- jakarta.jms:jakarta.jms-api:jar:3.1.0:provided
[INFO] |  +- jakarta.activation:jakarta.activation-api:jar:2.1.0:provided
[INFO] |  +- jakarta.mail:jakarta.mail-api:jar:2.1.0:provided
[INFO] |  +- jakarta.resource:jakarta.resource-api:jar:2.1.0:provided
[INFO] |  +- jakarta.authorization:jakarta.authorization-api:jar:2.1.0:provided
[INFO] |  \- jakarta.batch:jakarta.batch-api:jar:2.1.1:provided
[INFO] +- io.dropwizard.metrics:metrics-jersey2:jar:3.2.5:compile
[INFO] |  +- io.dropwizard.metrics:metrics-core:jar:3.2.5:compile
[INFO] |  \- io.dropwizard.metrics:metrics-annotation:jar:3.2.5:compile
[INFO] +- commons-lang:commons-lang:jar:2.6:compile
[INFO] +- com.idfconnect.ssorest.httpagent.framework:framework-core:jar:3.2.0-SNAPSHOT:compile
[INFO] |  +- io.protostuff:protostuff-core:jar:1.6.2:compile
[INFO] |  |  \- io.protostuff:protostuff-api:jar:1.6.2:compile
[INFO] |  +- io.protostuff:protostuff-runtime:jar:1.6.2:compile
[INFO] |  |  \- io.protostuff:protostuff-collectionschema:jar:1.6.2:compile
[INFO] |  +- org.slf4j:slf4j-ext:jar:2.0.3:compile
[INFO] |  +- com.idfconnect.ssorest.httpagent.framework:framework-annotations:jar:3.2.0-SNAPSHOT:compile
[INFO] |  +- com.idfconnect.ssorest.httpagent.framework:framework-common:jar:3.2.0-SNAPSHOT:compile
[INFO] |  +- com.idfconnect.ssorest:cache-core:jar:3.2.0-SNAPSHOT:compile
[INFO] |  +- com.idfconnect.framework:license:jar:1.0.8:compile
[INFO] |  +- com.konghq:unirest-java:jar:3.13.8:compile
[INFO] |  |  +- org.apache.httpcomponents:httpmime:jar:4.5.13:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore-nio:jar:4.4.13:compile
[INFO] |  |  \- org.apache.httpcomponents:httpasyncclient:jar:4.1.5:compile
[INFO] |  |     \- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  +- com.idfconnect.ssorest:cache-local:jar:3.2.0-SNAPSHOT:compile
[INFO] |  |  \- com.github.ben-manes.caffeine:caffeine:jar:2.8.0:compile
[INFO] |  +- com.idfconnect.ssorest:cache-redis:jar:3.2.0-SNAPSHOT:compile
[INFO] |  |  \- redis.clients:jedis:jar:2.9.0:compile
[INFO] |  +- com.idfconnect.ssorest:common-metrics:jar:3.2.0-SNAPSHOT:compile
[INFO] |  |  +- com.fasterxml.jackson.module:jackson-module-afterburner:jar:2.15.0:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-jvm:jar:3.2.5:compile
[INFO] |  |  \- org.elasticsearch.client:elasticsearch-rest-client:jar:6.1.2:compile
[INFO] |  +- org.apache.oltu.oauth2:org.apache.oltu.oauth2.client:jar:1.0.2:compile
[INFO] |  |  \- org.apache.oltu.oauth2:org.apache.oltu.oauth2.common:jar:1.0.2:compile
[INFO] |  |     \- org.json:json:jar:20140107:compile
[INFO] |  +- com.auth0:java-jwt:jar:3.11.0:compile
[INFO] |  +- com.nimbusds:nimbus-jose-jwt:jar:9.23:compile
[INFO] |  |  \- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
[INFO] |  +- org.bouncycastle:bcprov-jdk15on:jar:1.70:compile
[INFO] |  +- com.auth0:jwks-rsa:jar:0.15.0:compile
[INFO] |  \- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:3.0.1:compile
[INFO] +- commons-configuration:commons-configuration:jar:1.10:compile
[INFO] +- com.idfconnect.ssorest.gateway:gateway-api:jar:3.2.0-SNAPSHOT:compile
[INFO] +- com.nimbusds:c2id-server-jwkset-gen:jar:1.0:compile
[INFO] |  +- com.thetransactioncompany:pretty-json:jar:1.3.1:compile
[INFO] |  |  \- net.minidev:json-smart:jar:1.1.1:compile
[INFO] |  \- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO] \- com.sun.activation:jakarta.activation:jar:2.0.1:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.282 s
[INFO] Finished at: 2023-06-22T11:37:32-04:00
[INFO] ------------------------------------------------------------------------
```

**Comment by senivam** [comment]
I think io.dropwizard.metrics:metrics-jersey2 can do the thing. Because the referred version uses quite an old jersey: 
https://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-jersey2/3.2.5/metrics-jersey2-3.2.5.pom (2.11)
you could try the usage of metrics-jersey3 but that version also uses Jersey 3.0.4 which is not 3.1.x so I'm not sure what to use instead, but the dependency could go from there.

**Comment by senivam** [comment]
ah, my bad, there is metrics-jersey31:
https://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-jersey31/4.2.19/metrics-jersey31-4.2.19.pom
that is probably what you need :)

**Comment by rsandidfc** [comment]
Ugh, and I had my dependency for metrics explicitly exclude jersey so I didn't see the dependency in the hierarchy! You are a hero, thank you!!!
