### ISSUE TITLE
Connectivity issues masked by ProcessingException: Already connected

### ISSUE THREAD

**Issue by Avinash-B** [eclipse-ee4j/jersey#5523]
javax.ws.rs.ProcessingException: Already connected
    at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:263) ~[jersey-client.jar:?]
    at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:671) ~[jersey-client.jar:?]
    at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:668) ~[jersey-client.jar:?]
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common.jar:?]
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common.jar:?]
    at org.glassfish.jersey.internal.Errors.process(Errors.java:228) ~[jersey-common.jar:?]
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444) ~[jersey-common.jar:?]
    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:668) ~[jersey-client.jar:?]
    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:428) ~[jersey-client.jar:?]
    at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:334) ~[jersey-client.jar:?]

Related old issue  - https://github.com/eclipse-ee4j/jersey/issues/3000
This still looks to be masking some underlying issues and making it harder for us to pinpoint the exact cause of the problem.

**Comment by senivam** [comment]
which JDK, which Jersey, OS, probably more extended stack trace?

**Comment by jansupol** [comment]
A bug in the [JDK tracker](https://bugs.openjdk.org/browse/JDK-8163141) mentions the bug in the older version of Jersey.

Closing, since the version of Jersey in this issue is unknown.
