### ISSUE TITLE
UUID too large throws an exception and returns a 404 Not Found response, rather than being considered a 400 Bad Request

### ISSUE THREAD

**Issue by jamesforwardnwboxed** [eclipse-ee4j/jersey#5765]
When Jersey attempts to deserialise a bad request, where the controller/resource expects a `UUID` and is provided an invalid String that's too large to deserialise into a UUID, we get this stack trace and a `404` response:

```
Wrapped by: org.glassfish.jersey.internal.inject.ExtractorException: java.lang.IllegalArgumentException: UUID string too large
	
at org.glassfish.jersey.internal.inject.ParamConverters$AbstractStringReader.fromString(ParamConverters.java:102)
	
at org.glassfish.jersey.server.internal.inject.AbstractParamValueExtractor.convert(AbstractParamValueExtractor.java:116)
	
at org.glassfish.jersey.server.internal.inject.AbstractParamValueExtractor.fromString(AbstractParamValueExtractor.java:107)
	
at org.glassfish.jersey.server.internal.inject.SingleValueExtractor.extract(SingleValueExtractor.java:61)
	
at org.glassfish.jersey.server.internal.inject.PathParamValueParamProvider$PathParamValueProvider.apply(PathParamValueParamProvider.java:92)
```

I believe this should return a 400 Bad Request rather than `400` as the client is incorrectly calling the resource with an invalid value for UUID & doesn't adhere to the server's expectation of an actual UUID. The server throwing an exception also has downstream implications including error logging even though there's nothing wrong with the server, rather the client.

**Comment by jansupol** [comment]
The JAX-RS Spec, Section 3.2 says:
> Other exceptions thrown during
construction of field or property values using any of the 5 steps listed above are treated as client errors: if the
field or property is annotated with @MatrixParam, @QueryParam or @PathParam then an implementation
MUST generate an instance of NotFoundException (404 status) that wraps the thrown exception and no
entity; if the field or property is annotated with @HeaderParam or @CookieParam then an implementation
MUST generate an instance of BadRequestException (400 status) that wraps the thrown exception and
no entity.

So it dependents on whether you used `@QueryParam` or `@HeaderParam`.

**Comment by jansupol** [comment]
Closing as works as expected
